package view;

import entity.Cliente;
import bo.ClienteBO;
import dao.ClienteDAO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import test.Validar;

import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import static java.util.logging.Level.parse;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author Emilio
 */
public class FrmCliente extends javax.swing.JFrame {

    //Creates new form FrmCliente
    Cliente cliente = new Cliente();
    private ClienteBO clienteBO = new ClienteBO();
    private ClienteDAO clienteDAO = new ClienteDAO();

    public FrmCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Módulo - Gestión de Clientes");
        setResizable(false);
        listarClientes();
        txtNombre.requestFocus();

        //Integración de icono en la ventana de titulo de la ventana
        BufferedImage image = null;
        try {
            image = ImageIO.read(new File("src/icons/icons32px/logo30px.png"));
        } catch (IOException ex) {
            Logger.getLogger(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        setIconImage(image);
    }

    /**
     * 02-10-2020
     *
     * @author Emilio Método para cargar registros en la tabla clientes
     */
    public void listarClientes() {
        clienteBO.listarCliente(tblCliente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtArea = new javax.swing.JTextField();
        jdcFechaIngreso = new com.toedter.calendar.JDateChooser();
        btnAgregar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        btnEditar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtAreaEd = new javax.swing.JTextField();
        jdcFechaIngresoEd = new com.toedter.calendar.JDateChooser();
        txtCorreoEd = new javax.swing.JTextField();
        txtTelefonoEd = new javax.swing.JTextField();
        txtNombreEd = new javax.swing.JTextField();
        btnLimipiarEd = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jLabel11 = new javax.swing.JLabel();
        txtIdClienteBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        btnListar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 720));
        setMinimumSize(new java.awt.Dimension(1200, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 750));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(1100, 623));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(1100, 623));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1100, 623));
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Cliente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jLayeredPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(700, 416));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Teléfono:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Correo:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Fecha Ingreso:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Área de actuación:");

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtTelefono.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtCorreo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtArea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jdcFechaIngreso.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnAgregar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/anadir.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.setIconTextGap(25);
        btnAgregar.setPreferredSize(new java.awt.Dimension(100, 25));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/limpiar32px.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setIconTextGap(25);
        btnLimpiar.setPreferredSize(new java.awt.Dimension(100, 25));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtTelefono, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtCorreo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtArea, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jdcFechaIngreso, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnAgregar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnLimpiar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(24, 24, 24)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtArea, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(jdcFechaIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jdcFechaIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLayeredPane1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(487, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(461, 461, 461))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        jTabbedPane1.addTab("Agregar Cliente", jPanel1);

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edición de Cliente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jLayeredPane3.setPreferredSize(new java.awt.Dimension(700, 390));

        btnEditar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/guardar32px.png"))); // NOI18N
        btnEditar.setText("Guardar");
        btnEditar.setIconTextGap(20);
        btnEditar.setPreferredSize(new java.awt.Dimension(100, 25));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Nombre:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Teléfono:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Correo:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Fecha Ingreso:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Área de actuación:");

        txtAreaEd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jdcFechaIngresoEd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtCorreoEd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtTelefonoEd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtNombreEd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnLimipiarEd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLimipiarEd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/limpiar32px.png"))); // NOI18N
        btnLimipiarEd.setText("Limpiar");
        btnLimipiarEd.setIconTextGap(25);
        btnLimipiarEd.setPreferredSize(new java.awt.Dimension(100, 25));
        btnLimipiarEd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimipiarEdActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/eliminar32px.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setIconTextGap(20);
        btnEliminar.setPreferredSize(new java.awt.Dimension(100, 25));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLayeredPane3.setLayer(btnEditar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(txtAreaEd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jdcFechaIngresoEd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(txtCorreoEd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(txtTelefonoEd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(txtNombreEd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(btnLimipiarEd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(btnEliminar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAreaEd)
                            .addComponent(txtTelefonoEd)
                            .addComponent(txtCorreoEd)
                            .addComponent(jdcFechaIngresoEd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNombreEd, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnLimipiarEd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNombreEd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTelefonoEd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCorreoEd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9)
                    .addComponent(jdcFechaIngresoEd, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAreaEd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimipiarEd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLayeredPane4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Cliente por Id", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Id Cliente:");

        txtIdClienteBuscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/buscar32px.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setIconTextGap(20);
        btnBuscar.setPreferredSize(new java.awt.Dimension(100, 25));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLayeredPane4.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(txtIdClienteBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(btnBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(txtIdClienteBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(448, 448, 448))
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtIdClienteBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro de Clientes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        tblCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblCliente.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblCliente.setMaximumSize(null);
        tblCliente.setMinimumSize(null);
        jScrollPane1.setViewportView(tblCliente);

        btnListar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/listar32px.png"))); // NOI18N
        btnListar.setText("Listar");
        btnListar.setIconTextGap(25);
        btnListar.setPreferredSize(new java.awt.Dimension(100, 25));
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        jLayeredPane2.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(btnListar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLayeredPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayeredPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ver Clientes", jPanel2);

        btnVolver.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/volver32px.png"))); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.setIconTextGap(30);
        btnVolver.setPreferredSize(new java.awt.Dimension(100, 25));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1493, Short.MAX_VALUE))
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        new FrmPanelGeneral().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        listarClientes();
    }//GEN-LAST:event_btnListarActionPerformed

    /**
     * 05-10-2020
     *
     * @author Emilio Método de busqueda Conversión de datos y Asignación de
     * datos La fechaIngreso es capturada desde la BD en formato [Date],
     * posterior convertida en formato [String] en el arreglo en posición
     * vector[4] posterior transformada a formato [SimpleDateFormat] posterior
     * transformada a formato [Date] para mostrarse en el JDateChooser
     */
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String idClienteString = txtIdClienteBuscar.getText();

        if (validacionIdCliente(idClienteString) == true) {
            String[] vector = new String[6];
            int idClienteInt = Integer.parseInt(txtIdClienteBuscar.getText());
            vector = clienteBO.buscarCliente(idClienteInt);

            txtNombreEd.setText(vector[1]);
            txtTelefonoEd.setText(vector[2]);
            txtCorreoEd.setText(vector[3]);
            txtAreaEd.setText(vector[5]);

            try {
                String fechaString = vector[4];
                SimpleDateFormat fechaSimpleDate = new SimpleDateFormat("yyyy-MM-dd");
                Date fechaDate = fechaSimpleDate.parse(fechaString);

//                //TESTING: Verificación del tipo de dato fecha
//                System.out.println("fechaString: " + fechaString);
//                System.out.println("fechaSimpleDate: " + fechaSimpleDate);
//                System.out.println("fechaDate: " + fechaDate);
//                System.out.println("Tipo variable vector[4]: " + vector[4].getClass().getSimpleName());
                jdcFechaIngresoEd.setDate(fechaDate);

                //*** se bloquea o deshabilita el campo de busqueda ***
                txtIdClienteBuscar.setEnabled(false);
                
            } catch (ParseException ex) {
                //System.out.println("Fecha en formato incorrecto!");
                Logger.getLogger(FrmCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimipiarEdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimipiarEdActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimipiarEdActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        //Asignación de campos
        String nombreEd = txtNombreEd.getText();
        String telefonoEd = txtTelefonoEd.getText();
        String correoEd = txtCorreoEd.getText();
        String areaEd = txtAreaEd.getText();
        String idClienteString = txtIdClienteBuscar.getText();

        //Validación de campos
        if (validacionEdicion(nombreEd, telefonoEd, correoEd, areaEd, idClienteString) == true) {

            //Conversión de dato tipo fecha a string
            SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-YYYY");
            String fecha = dFormat.format(jdcFechaIngresoEd.getDate());

            //Conversion de dato tipo String a int
            //int fono = Integer.parseInt(txtTelefonoEd.getText());
            //int fono = Integer.valueOf(txtTelefonoEd.getText()).intValue();
            String fonoString = txtTelefonoEd.getText().trim();
            //int fonoInt = Integer.parseInt(fonoString);
            long fonoLong = Long.parseLong(fonoString);

            int idCliente = Integer.valueOf(txtIdClienteBuscar.getText()).intValue();

            //Instanciación y Asignación de valores capturados
            //Cliente cliente = new Cliente();
            cliente.setIdCliente(idCliente);
            cliente.setNombre(nombreEd);
            //cliente.setTelefono(fonoInt);
            cliente.setTelefono(fonoLong);
            cliente.setCorreo(correoEd);
            cliente.setFechaIngreso(fecha);
            cliente.setAreaActuacion(areaEd);

            String mensaje = clienteBO.modificarCliente(cliente);
            JOptionPane.showMessageDialog(null, mensaje, "Infomación", JOptionPane.INFORMATION_MESSAGE);

            //TESTING: Verificación del tipo de dato fecha
            //System.out.println("Variable fecha es de tipo: " + fecha.getClass().getSimpleName());
            limpiarCampos();
            listarClientes();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * 05-10-2020
     *
     * @autor Emilio AGREGAR NUEVO CLIENTE
     */
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        String nombre = txtNombre.getText();
        String fonoString = txtTelefono.getText();
        String correo = txtCorreo.getText();
        String area = txtArea.getText();

        if (validacionAgregar(nombre, fonoString, correo, area) == true) {

            //Conversión de dato tipo fecha a string
            SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-YYYY");
            String fecha = dFormat.format(jdcFechaIngreso.getDate());

            //Conversion de dato tipo String a int
            //int fonoInt = Integer.parseInt(fonoString);
            //int fonoInt = Integer.parseInt(txtTelefono.getText());
            long fonoLong = Long.parseLong(txtTelefono.getText());

            //Instanciación y Asignación de valores capturados
            //Cliente cliente = new Cliente();
            cliente.setNombre(nombre);
            //cliente.setTelefono(fonoInt);
            cliente.setTelefono(fonoLong);
            cliente.setCorreo(correo);
            cliente.setFechaIngreso(fecha);
            cliente.setAreaActuacion(area);

            String mensaje = clienteBO.agregarCliente(cliente);
            JOptionPane.showMessageDialog(null, mensaje, "Infomación", JOptionPane.INFORMATION_MESSAGE);
            //mostrarMensaje("Datos del formulario validados correctamente!");
            limpiarCampos();
            listarClientes();

            // TESTING: validación de variables
            /*System.out.println("******************************");
            System.out.println("Datos");
            System.out.println("Nombre: " + nombre);
            System.out.println("Telefono: " + fonoLong);
            System.out.println("Correo: " + correo);
            System.out.println("Fecha: " + fecha);
            System.out.println("Area: " + area);*/
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    //ELIMINAR CLIENTE
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String idClienteString = txtIdClienteBuscar.getText();

        if (validacionIdCliente(idClienteString) == true) {
            //ClienteBO clienteBO = new ClienteBO();
            int idClienteInt = Integer.parseInt(txtIdClienteBuscar.getText());

            //Mensaje de Verificación
            int respuesta = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar al Cliente?", "Confirmación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

            // 0 = Si
            if (respuesta == 0) {
                String mensaje = clienteBO.eliminarCliente(idClienteInt);
                JOptionPane.showMessageDialog(null, mensaje);
                limpiarCampos();
                listarClientes();
            } else {
                JOptionPane.showMessageDialog(null, "Eliminación cancelada!", "Infomación", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        /*if (this.jTabbedPane1.getSelectedIndex() == 1) {
            System.out.println("Ingreso a pestaña 2");
            listarClientes();
        }*/
    }//GEN-LAST:event_jTabbedPane1StateChanged

    /**
     * 02-12-2020
     *
     * @author Emilio
     * @throws el boton cerrar cierra la ventana actual y abre la ventana del
     * menu general del sistema
     */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new FrmPanelGeneral().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private boolean validacionIdCliente(String idClienteString) {

        //Validar que el campo de busqueda no esté vacío
        if (Validar.campoVacio(idClienteString) == false) {
            mostrarMensaje("Error: \nEl campo está vacío! \nDebe completar el campo.");
            txtIdClienteBuscar.grabFocus();
            limpiarCampos();
            return false;
        }

        //Validar que el campo de busqueda sea numérico
        if (Validar.numeroEntero(idClienteString) == false) {
            mostrarMensaje("Error: \nEl dato ingresado debe ser numérico!");
            txtIdClienteBuscar.grabFocus();
            limpiarCampos();
            return false;
        }

        //Validar que idCliente exista
        //ClienteBO clienteBO = new ClienteBO();
        int idClienteInt = Integer.parseInt(idClienteString);
        String[] vector = new String[6];
        vector = clienteBO.buscarCliente(idClienteInt);
        String idCliente = vector[0];

        if (idCliente == "") {
            mostrarMensaje("Error: \nEl id ingresado no existe!");
            txtIdClienteBuscar.grabFocus();
            limpiarCampos();
            return false;
        }
        return true;
    }

    public void limpiarCampos() {
        txtIdClienteBuscar.setText("");
        txtNombre.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
        jdcFechaIngreso.setCalendar(null);
        txtArea.setText("");
        txtNombreEd.setText("");
        txtTelefonoEd.setText("");
        txtCorreoEd.setText("");
        jdcFechaIngresoEd.setCalendar(null);
        txtAreaEd.setText("");
        txtIdClienteBuscar.setEnabled(true);
    }

    /**
     * 05-10-2020
     *
     *
     * @autor Emilio Método de validación de campos del formulario El método usa
     * la clase Validar.java Ruta: com.admintaskv2.cl.test.Validar
     */
    private boolean validacionAgregar(String nombre, String telefono, String correo, String area) {

        //Validación de los campos no estén vacíos o solo con espacios en blanco
        if (Validar.campoVacio(nombre) == false) {
            mostrarMensaje("Error: \nEl nombre está vacío! \nDebe completar el campo.");
            txtNombre.grabFocus(); //Dar el enfoque al control
            return false;
        }

        if (Validar.campoVacio(telefono) == false) {
            mostrarMensaje("Error: \nEl teléfono está vacío! \nDebe completar el campo.");
            txtTelefono.grabFocus(); //Dar el enfoque al control
            return false;
        }

        if (Validar.campoVacio(correo) == false) {
            mostrarMensaje("Error: \nEl correo está vacío! \nDebe completar el campo.");
            txtCorreo.grabFocus(); //Dar el enfoque al control
            return false;
        }

        if (jdcFechaIngreso.getDate() == null) {
            mostrarMensaje("Error: \nLa fecha está vacía! \nDebe completar el campo.");
            jdcFechaIngreso.grabFocus(); //Dar el enfoque al control
            return false;
        }

        if (Validar.campoVacio(area) == false) {
            mostrarMensaje("Error: \nEl área está vacía! \nDebe completar el campo.");
            txtArea.grabFocus(); //Dar el enfoque al control
            return false;
        }

        //validar el largo del telefono
//        int numCaracteres = 9;
//        if (telefono.length() > numCaracteres) {
//            mostrarMensaje("Error: \nEl teléfono debe tener máximo 9 dígitos");
//            return false;
//        }
        if (Validar.largoTelefono(telefono) == false) {
            mostrarMensaje("Error: \nEl teléfono debe tener máximo 11 dígitos");
            txtTelefono.grabFocus();
            return false;
        }

        //Validar los datos numéricos
        if (Validar.numeroEntero(telefono) == false) {
            mostrarMensaje("Error: \nEl teléfono no es válido! \nDebe contener solo números.");
            txtTelefono.grabFocus(); //Dar el enfoque al control
            return false;
        }

        return true;
    }

    private boolean validacionEdicion(String nombreEd, String telefonoEd, String correoEd, String areaEd, String idClienteString) {

        //Validacion de campo vacio de id
        if (idClienteString.isEmpty()) {
            mostrarMensaje("Error: \nEl id está vacío! \nDebe completar el campo.");
            txtNombreEd.grabFocus(); //Dar el enfoque al control
            return false;
        }

        //Validacion de campo id como caracter
        if (Validar.numeroInt(idClienteString) == false) {
            mostrarMensaje("Error: \nEl id está debe ser numérico!");
            txtNombreEd.grabFocus(); //Dar el enfoque al control
            return false;
        }

        //Validación de los campos no estén vacíos o solo con espacios en blanco
        if (Validar.campoVacio(nombreEd) == false) {
            mostrarMensaje("Error: \nEl nombre está vacío! \nDebe completar el campo.");
            txtNombreEd.grabFocus(); //Dar el enfoque al control
            return false;
        }

        if (Validar.campoVacio(telefonoEd) == false) {
            mostrarMensaje("Error: \nEl teléfono está vacío! \nDebe completar el campo.");
            txtTelefonoEd.grabFocus(); //Dar el enfoque al control
            return false;
        }

        if (Validar.campoVacio(correoEd) == false) {
            mostrarMensaje("Error: \nEl correo está vacío! \nDebe completar el campo.");
            txtCorreoEd.grabFocus(); //Dar el enfoque al control
            return false;
        }

        if (jdcFechaIngresoEd.getDate() == null) {
            mostrarMensaje("Error: \nLa fecha está vacía! \nDebe completar el campo.");
            jdcFechaIngresoEd.grabFocus(); //Dar el enfoque al control
            return false;
        }

        if (Validar.campoVacio(areaEd) == false) {
            mostrarMensaje("Error: \nEl área está vacía! \nDebe completar el campo.");
            txtAreaEd.grabFocus(); //Dar el enfoque al control
            return false;
        }

        //validar el largo del telefono
//        int numCaracteres = 9;
//        if (telefonoEd.length() > numCaracteres) {
//            mostrarMensaje("Error: \nEl teléfono debe tener máximo 9 dígitos");
//            return false;
//        }
        if (Validar.largoTelefono(telefonoEd) == false) {
            mostrarMensaje("Error: \nEl teléfono debe tener máximo 11 dígitos");
            txtTelefonoEd.grabFocus();
            return false;
        }

        //Validar los datos numéricos
        if (Validar.numeroEntero(telefonoEd) == false) {
            mostrarMensaje("Error: \nEl teléfono no es válido! \nDebe contener solo números.");
            txtTelefonoEd.grabFocus(); //Dar el enfoque al control
            return false;
        }

        return true;
    }

    //Método común para mostrar mensajes
    private void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje);
    }

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
    public void frmCliente() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCliente().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimipiarEd;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.toedter.calendar.JDateChooser jdcFechaIngreso;
    private com.toedter.calendar.JDateChooser jdcFechaIngresoEd;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtAreaEd;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtCorreoEd;
    private javax.swing.JTextField txtIdClienteBuscar;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreEd;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefonoEd;
    // End of variables declaration//GEN-END:variables
}
