package view;

import entity.Estado;
import bo.EstadoBO;
import dao.EstadoDAO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import test.Validar;

import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import static java.util.logging.Level.parse;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author Emilio
 */
public class FrmEstado extends javax.swing.JFrame {

    //Creates new form FrmEstado
    Estado estado = new Estado();
    private EstadoBO estadoBO = new EstadoBO();
    private EstadoDAO estadoDAO = new EstadoDAO();

    public FrmEstado() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Módulo - Gestión de Estado");
        setResizable(false);
        txtNombre.requestFocus();
        listarEstados();
        txtIdEstadoBuscar.setEnabled(true);

        //Integración de icono en la ventana de titulo de la ventana
        BufferedImage image = null;
        try {
            image = ImageIO.read(new File("src/icons/icons32px/logo30px.png"));
        } catch (IOException ex) {
            Logger.getLogger(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        setIconImage(image);
    }

    /**
     * 02-10-2020 Método para cargar registros en la tabla
     */
    public void listarEstados() {
        estadoBO.listarEstado(tblEstado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        btnEditar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnLimipiarEd = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtNombreEd = new javax.swing.JTextField();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jLabel11 = new javax.swing.JLabel();
        txtIdEstadoBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEstado = new javax.swing.JTable();
        btnListar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Estado", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(700, 249));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Nombre del estado:");

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnAgregar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/anadir.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.setIconTextGap(20);
        btnAgregar.setPreferredSize(new java.awt.Dimension(100, 25));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/limpiar32px.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setIconTextGap(20);
        btnLimpiar.setPreferredSize(new java.awt.Dimension(100, 25));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnAgregar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnLimpiar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(0, 238, Short.MAX_VALUE)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNombre))
                .addGap(64, 64, 64))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(330, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(329, 329, 329))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar Estado", jPanel1);

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edición de Estado", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jLayeredPane3.setPreferredSize(new java.awt.Dimension(700, 182));

        btnEditar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/guardar32px.png"))); // NOI18N
        btnEditar.setText("Guardar");
        btnEditar.setIconTextGap(20);
        btnEditar.setPreferredSize(new java.awt.Dimension(100, 25));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Nombre del estado:");

        btnLimipiarEd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLimipiarEd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/limpiar32px.png"))); // NOI18N
        btnLimipiarEd.setText("Limpiar");
        btnLimipiarEd.setIconTextGap(20);
        btnLimipiarEd.setPreferredSize(new java.awt.Dimension(100, 25));
        btnLimipiarEd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimipiarEdActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/eliminar32px.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setIconTextGap(20);
        btnEliminar.setPreferredSize(new java.awt.Dimension(100, 25));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtNombreEd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNombreEd.setPreferredSize(new java.awt.Dimension(6, 25));

        jLayeredPane3.setLayer(btnEditar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(btnLimipiarEd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(btnEliminar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(txtNombreEd, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(btnLimipiarEd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombreEd, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNombreEd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimipiarEd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLayeredPane4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Estado por Id", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Id Estado:");

        txtIdEstadoBuscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtIdEstadoBuscar.setEnabled(false);
        txtIdEstadoBuscar.setPreferredSize(new java.awt.Dimension(6, 25));

        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/buscar32px.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setIconTextGap(20);
        btnBuscar.setPreferredSize(new java.awt.Dimension(100, 25));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLayeredPane4.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(txtIdEstadoBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(btnBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(txtIdEstadoBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtIdEstadoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro de Estados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblEstado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblEstado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblEstado.setRowHeight(18);
        jScrollPane1.setViewportView(tblEstado);

        jLayeredPane2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 400, 300));

        btnListar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/listar32px.png"))); // NOI18N
        btnListar.setText("Listar");
        btnListar.setIconTextGap(20);
        btnListar.setPreferredSize(new java.awt.Dimension(100, 25));
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        jLayeredPane2.add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 150, 40));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayeredPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
                    .addComponent(jLayeredPane4))
                .addGap(105, 105, 105)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60))
        );

        jTabbedPane1.addTab("Ver Estados", jPanel2);

        btnVolver.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/volver32px.png"))); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.setIconTextGap(20);
        btnVolver.setPreferredSize(new java.awt.Dimension(100, 25));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        new FrmPanelGeneral().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        /*if (this.jTabbedPane1.getSelectedIndex() == 1) {
            System.out.println("Ingreso a pestaña 2");
            listarEstados();
        }*/
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        listarEstados();
    }//GEN-LAST:event_btnListarActionPerformed

    /**
     * 06-10-2020
     *
     * @author Emilio Método de busqueda
     */
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String idEstadoString = txtIdEstadoBuscar.getText();

        if (validacionIdEstado(idEstadoString) == true) {
            String[] vector = new String[2];
            int idEstadoInt = Integer.parseInt(txtIdEstadoBuscar.getText());
            vector = estadoBO.buscarEstado(idEstadoInt);
            txtNombreEd.setText(vector[1]);

            //*** se bloquea o deshabilita el campo de busqueda ***
            txtIdEstadoBuscar.setEnabled(false);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    //ELIMINAR CLIENTE
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String idEstadoString = txtIdEstadoBuscar.getText();

        if (validacionIdEstado(idEstadoString) == true) {
            //EstadoBO estadoBO = new EstadoBO();
            int idEstadoInt = Integer.parseInt(txtIdEstadoBuscar.getText());

            if (idEstadoInt <= 9) {
                //JOptionPane.showConfirmDialog(null, "Por seguridad \n(No) es posible eliminar el Estado!", "Información");
                String mensaje = "Por seguridad \n(No) es posible eliminar el Estado!";
                mostrarMensaje(mensaje);
            } else {

                //Mensaje de Verificación
                int respuesta = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar el Estado?", "Confirmación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

                // 0 = Si
                if (respuesta == 0) {
                    String mensaje = estadoBO.eliminarEstado(idEstadoInt);
                    JOptionPane.showMessageDialog(null, mensaje);
                    limpiarCampos();
                    listarEstados();
                } else {
                    JOptionPane.showMessageDialog(null, "Eliminación cancelada!", "Infomación", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimipiarEdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimipiarEdActionPerformed
        limpiarCampos();

    }//GEN-LAST:event_btnLimipiarEdActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        //Asignación de campos
        String nombreEd = txtNombreEd.getText();
        String idEstadoString = txtIdEstadoBuscar.getText();

        //Validación de campos
        if (validacionEdicion(nombreEd, idEstadoString) == true) {
            
            int idEstado = Integer.parseInt(idEstadoString);
            
            if (idEstado <= 9) {
                String mensaje = "Por seguridad \n(No) es posible editar el Estado!";
                mostrarMensaje(mensaje);                
            } else {
            //txtIdEstadoBuscar.setEnabled(false);
            //Conversion de dato tipo String a int
            //int idEstado = Integer.parseInt(txtIdEstadoBuscar.getText());         
            //Instanciación y Asignación de valores capturados
            //Estado estado = new Estado();
            estado.setIdEstado(idEstado);
            estado.setDescripcion(nombreEd);

            String mensaje = estadoBO.modificarEstado(estado);
            JOptionPane.showMessageDialog(null, mensaje, "Infomación", JOptionPane.INFORMATION_MESSAGE);

            //TESTING: Verificación del tipo de dato fecha
            //System.out.println("Variable fecha es de tipo: " + fecha.getClass().getSimpleName());
            limpiarCampos();
            listarEstados();
            }
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * 05-10-2020
     *
     * @autor Emilio AGREGAR NUEVO CLIENTE
     */
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String nombre = txtNombre.getText();

        if (validacionAgregar(nombre) == true) {

            //Instanciación y Asignación de valores capturados
            //Estado estado = new Estado();
            estado.setDescripcion(nombre);

            String mensaje = estadoBO.agregarEstado(estado);
            JOptionPane.showMessageDialog(null, mensaje, "Infomación", JOptionPane.INFORMATION_MESSAGE);
            //mostrarMensaje("Datos del formulario validados correctamente!");
            limpiarCampos();
            listarEstados();

            // TESTING: validación de variables
            //System.out.println("******************************");
            //System.out.println("Datos");
            //System.out.println("Nombre: " + nombre);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    /**
     * 02-12-2020
     *
     * @author Emilio
     * @throws el boton cerrar cierra la ventana actual y abre la ventana del
     * menu general del sistema
     */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new FrmPanelGeneral().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private boolean validacionIdEstado(String idEstadoString) {

        //Validar que el campo de busqueda no esté vacío
        if (Validar.campoVacio(idEstadoString) == false) {
            mostrarMensaje("Error: \nEl campo está vacío! \nDebe completar el campo.");
            txtIdEstadoBuscar.grabFocus();
            limpiarCampos();
            return false;
        }

        //Validar que el campo de busqueda sea numérico
        if (Validar.numeroEntero(idEstadoString) == false) {
            mostrarMensaje("Error: \nEl dato ingresado debe ser numérico!");
            txtIdEstadoBuscar.grabFocus();
            limpiarCampos();
            return false;
        }

        //Validar que id exista
        //EstadoBO estadoBO = new EstadoBO();
        int idEstadoInt = Integer.parseInt(idEstadoString);
        String[] vector = new String[2];
        vector = estadoBO.buscarEstado(idEstadoInt);
        String idEstado = vector[0];

        if (idEstado == "") {
            mostrarMensaje("Error: \nEl id ingresado no existe!");
            txtIdEstadoBuscar.grabFocus();
            limpiarCampos();
            return false;
        }
        return true;
    }

    public void limpiarCampos() {
        txtIdEstadoBuscar.setText("");
        txtNombre.setText("");
        txtNombreEd.setText("");
        txtIdEstadoBuscar.setEnabled(true);
    }

    /**
     * 05-10-2020
     *
     *
     * @autor Emilio Método de validación de campos del formulario El método usa
     * la clase test.Validar
     */
    private boolean validacionAgregar(String nombre) {

        //Validación de los campos no estén vacíos o solo con espacios en blanco
        if (Validar.campoVacio(nombre) == false) {
            mostrarMensaje("Error: \nEl nombre está vacío! \nDebe completar el campo.");
            txtNombre.grabFocus(); //Dar el enfoque al control
            return false;
        }
        return true;
    }

    private boolean validacionEdicion(String nombreEd, String idEstadoString) {

        //Validacion de campo id buscar que no sea vacío
        /*if (Validar.campoVacio(idEstadoString) == false){
            mostrarMensaje("Error: \nEl id está vacío! \nDebe completar el campo.");
            txtNombreEd.grabFocus(); //Dar el enfoque al control
            return false;
        }*/
        //Validacion de campo id buscar que sea numérico
        /*if (Validar.numeroInt(idEstadoString) == false){
            mostrarMensaje("Error: \nEl id debe ser numérico.");
            txtNombreEd.grabFocus(); //Dar el enfoque al control
            return false;
        }*/
        //Validación de los campos no estén vacíos o solo con espacios en blanco
        if (Validar.campoVacio(nombreEd) == false) {
            mostrarMensaje("Error: \nEl nombre está vacío! \nDebe completar el campo.");
            txtNombreEd.grabFocus(); //Dar el enfoque al control
            return false;
        }
        return true;
    }

    //Método común para mostrar mensajes
    private void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje);
    }

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
    public void frmEstado() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEstado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimipiarEd;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblEstado;
    private javax.swing.JTextField txtIdEstadoBuscar;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreEd;
    // End of variables declaration//GEN-END:variables
}
