package view;

import bo.UsuarioBO;
import dao.UsuarioDAO;
import bo.UnidadBO;
import dao.UnidadDAO;
import bo.ProcesoBO;
import dao.ProcesoDAO;
import bo.EstadoBO;
import dao.EstadoDAO;
import entity.Funcion;
import bo.FuncionBO;
import dao.FuncionDAO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import test.Validar;

import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import static java.util.logging.Level.parse;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

// LIBRERIA DE ENCRIPTACIÓN
// ALGORITMO DE ENCRIPTACIÓN SHA 512 HEX
import org.apache.commons.codec.digest.DigestUtils;

/**
 *
 * @author Thomas
 */
public class FrmFuncion extends javax.swing.JFrame {

    Funcion funcion = new Funcion();

    private FuncionBO funcionBO = new FuncionBO();
    private FuncionDAO funcionDAO = new FuncionDAO();

    private UsuarioBO usuarioBO = new UsuarioBO();
    private UsuarioDAO usuarioDAO = new UsuarioDAO();

    private ProcesoBO procesoBO = new ProcesoBO();
    private ProcesoDAO procesoDAO = new ProcesoDAO();

    private UnidadBO unidadBO = new UnidadBO();
    private UnidadDAO unidadDao = new UnidadDAO();

    private EstadoBO estadoBO = new EstadoBO();
    private EstadoDAO estadoDAO = new EstadoDAO();

    //public int idProcesoInt;

    public FrmFuncion() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Módulo - Gestión de Funciones");
        setResizable(false);
        listarFuncion();
        txtNombre.requestFocus();
        listarUsuarios();
//        listarProcesos();
        listarUnidades();
        listarEstados();

        //Integración de icono en la ventana de titulo de la ventana
        BufferedImage image = null;
        try {
            image = ImageIO.read(new File("src/icons/icons32px/logo30px.png"));
        } catch (IOException ex) {
            Logger.getLogger(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        setIconImage(image);
    }

    // 01-12-2020
    // Thomas Método para cargar registros en la tabla funciones
    public void listarFuncion() {
        funcionBO.listarFuncion(tblFuncion);
    }

    // Cargar datos desde BD en combobox
    public void listarUsuarios() {
        usuarioBO.listarUsuarioCmb(cmbUsuario);
        usuarioBO.listarUsuarioCmb(cmbUsuarioEd);
    }

//        public void listarProcesos() {
//        procesoBO.listarProcesoCmb(cmbProceso);
//        procesoBO.listarProcesoCmb(cmbProcesoEd);
//    }
    public void listarUnidades() {
        unidadBO.listarUnidadCmb(cmbUnidad);
        unidadBO.listarUnidadCmb(cmbUnidadEd);
    }

    public void listarEstados() {
        estadoBO.listarEstadoCmb(cmbEstado);
        estadoBO.listarEstadoCmb(cmbEstadoEd);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblNombre = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        lblFechaInicio = new javax.swing.JLabel();
        lblFechaTermino = new javax.swing.JLabel();
        lblUnidad = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        cmbUnidad = new javax.swing.JComboBox<>();
        cmbUsuario = new javax.swing.JComboBox<>();
        jdcFechaInicio = new com.toedter.calendar.JDateChooser();
        jdcFechaTermino = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jLabel11 = new javax.swing.JLabel();
        txtIdFuncionBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        btnEditar = new javax.swing.JButton();
        btnLimipiarEd = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblNombre1 = new javax.swing.JLabel();
        txtNombreEd = new javax.swing.JTextField();
        lblFechaInicioEd = new javax.swing.JLabel();
        lblFechaTerminoEd = new javax.swing.JLabel();
        lblUnidadEd = new javax.swing.JLabel();
        cmbUnidadEd = new javax.swing.JComboBox<>();
        lblEstadoEd = new javax.swing.JLabel();
        cmbEstadoEd = new javax.swing.JComboBox<>();
        cmbUsuarioEd = new javax.swing.JComboBox<>();
        lblUsuarioEd = new javax.swing.JLabel();
        jdcFechaInicioEd = new com.toedter.calendar.JDateChooser();
        jdcFechaTerminoEd = new com.toedter.calendar.JDateChooser();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFuncion = new javax.swing.JTable();
        btnListar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1867, 830));
        setPreferredSize(new java.awt.Dimension(1867, 830));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1200, 700));
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de la Función", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jLayeredPane1.setMaximumSize(new java.awt.Dimension(700, 588));
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(700, 588));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombre.setText("Nombre:");
        jLayeredPane1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsuario.setText("Usuario:");
        jLayeredPane1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        lblEstado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEstado.setText("Estado:");
        jLayeredPane1.add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLayeredPane1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 300, -1));

        btnAgregar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/anadir.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.setIconTextGap(20);
        btnAgregar.setPreferredSize(new java.awt.Dimension(100, 25));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 490, 150, 40));

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/limpiar32px.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setIconTextGap(20);
        btnLimpiar.setPreferredSize(new java.awt.Dimension(100, 25));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 150, 40));

        lblFechaInicio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFechaInicio.setText("Fecha Inicio:");
        jLayeredPane1.add(lblFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        lblFechaTermino.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFechaTermino.setText("Fecha Término");
        jLayeredPane1.add(lblFechaTermino, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        lblUnidad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUnidad.setText("Unidad:");
        jLayeredPane1.add(lblUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        cmbEstado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLayeredPane1.add(cmbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 300, -1));

        cmbUnidad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLayeredPane1.add(cmbUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 300, -1));

        cmbUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLayeredPane1.add(cmbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 300, -1));

        jdcFechaInicio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLayeredPane1.add(jdcFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 300, 30));

        jdcFechaTermino.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLayeredPane1.add(jdcFechaTermino, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 300, 30));

        jPanel1.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 11, 570, 590));
        jLayeredPane1.getAccessibleContext().setAccessibleName("Datos del");

        jTabbedPane1.addTab("Agregar Funcion", jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(573, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Función por Id", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jLayeredPane4.setMaximumSize(new java.awt.Dimension(600, 94));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Id Función:");

        txtIdFuncionBuscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/buscar32px.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setIconTextGap(20);
        btnBuscar.setPreferredSize(new java.awt.Dimension(100, 25));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLayeredPane4.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(txtIdFuncionBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(btnBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(27, 27, 27)
                .addComponent(txtIdFuncionBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtIdFuncionBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jLayeredPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 29, -1, -1));

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edición de Función", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jLayeredPane3.setMaximumSize(new java.awt.Dimension(600, 495));

        btnEditar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/guardar32px.png"))); // NOI18N
        btnEditar.setText("Guardar");
        btnEditar.setIconTextGap(20);
        btnEditar.setPreferredSize(new java.awt.Dimension(100, 25));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnLimipiarEd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLimipiarEd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/limpiar32px.png"))); // NOI18N
        btnLimipiarEd.setText("Limpiar");
        btnLimipiarEd.setIconTextGap(20);
        btnLimipiarEd.setPreferredSize(new java.awt.Dimension(100, 25));
        btnLimipiarEd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimipiarEdActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/eliminar32px.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setIconTextGap(20);
        btnEliminar.setPreferredSize(new java.awt.Dimension(100, 25));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lblNombre1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombre1.setText("Nombre:");

        txtNombreEd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblFechaInicioEd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFechaInicioEd.setText("Fecha Inicio:");

        lblFechaTerminoEd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFechaTerminoEd.setText("Fecha Término");

        lblUnidadEd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUnidadEd.setText("Unidad:");

        cmbUnidadEd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblEstadoEd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEstadoEd.setText("Estado:");

        cmbEstadoEd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cmbUsuarioEd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblUsuarioEd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsuarioEd.setText("Usuario:");

        jdcFechaInicioEd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jdcFechaTerminoEd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLayeredPane3.setLayer(btnEditar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(btnLimipiarEd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(btnEliminar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(lblNombre1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(txtNombreEd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(lblFechaInicioEd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(lblFechaTerminoEd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(lblUnidadEd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(cmbUnidadEd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(lblEstadoEd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(cmbEstadoEd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(cmbUsuarioEd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(lblUsuarioEd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jdcFechaInicioEd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jdcFechaTerminoEd, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEstadoEd)
                            .addComponent(lblUsuarioEd)
                            .addComponent(lblNombre1)
                            .addComponent(lblFechaInicioEd)
                            .addComponent(lblUnidadEd)
                            .addComponent(lblFechaTerminoEd))
                        .addGap(68, 68, 68)
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreEd)
                            .addComponent(jdcFechaInicioEd, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                            .addComponent(jdcFechaTerminoEd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbUnidadEd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbEstadoEd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbUsuarioEd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane3Layout.createSequentialGroup()
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnLimipiarEd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre1)
                    .addComponent(txtNombreEd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFechaInicioEd)
                    .addComponent(jdcFechaInicioEd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFechaTerminoEd)
                    .addComponent(jdcFechaTerminoEd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUnidadEd)
                    .addComponent(cmbUnidadEd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbEstadoEd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstadoEd))
                .addGap(30, 30, 30)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuarioEd)
                    .addComponent(cmbUsuarioEd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimipiarEd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );

        jPanel2.add(jLayeredPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 146, 624, 510));

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro de Funciones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jScrollPane1.setBorder(null);

        tblFuncion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblFuncion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblFuncion.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jScrollPane1.setViewportView(tblFuncion);

        btnListar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/listar32px.png"))); // NOI18N
        btnListar.setText("Listar");
        btnListar.setIconTextGap(20);
        btnListar.setPreferredSize(new java.awt.Dimension(100, 25));
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        jLayeredPane2.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(btnListar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1148, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(663, 29, -1, 620));

        jTabbedPane1.addTab("Ver Funciones", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1867, 700));

        btnVolver.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/volver32px.png"))); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.setIconTextGap(20);
        btnVolver.setPreferredSize(new java.awt.Dimension(100, 25));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 730, 150, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        new FrmPanelGeneral().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    // 01-12-2020
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String idFuncionString = txtIdFuncionBuscar.getText();

        if (validacionIdFuncion(idFuncionString) == true) {

            //String[] vector = new String[8];
            String[] vector = new String[7];
            int idFuncionInt = Integer.parseInt(txtIdFuncionBuscar.getText());
            vector = funcionBO.buscarFuncion(idFuncionInt);

            txtNombreEd.setText(vector[1]);

            // (10-12-2020) (Emilio) (se bloquea o deshabilita el campo de busqueda)
            txtIdFuncionBuscar.setEnabled(false);

            try {
                String fechaInicioEdString = vector[2];
                SimpleDateFormat fechaSimpleDate = new SimpleDateFormat("yyyy-MM-dd");
                Date fechaDate = fechaSimpleDate.parse(fechaInicioEdString);
                jdcFechaInicioEd.setDate(fechaDate);
            } catch (ParseException ex) {
                //System.out.println("Fecha en formato incorrecto!");
                Logger.getLogger(FrmCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                String fechaTerminoEdString = vector[3];
                SimpleDateFormat fechaSimpleDate = new SimpleDateFormat("yyyy-MM-dd");
                Date fechaDate = fechaSimpleDate.parse(fechaTerminoEdString);
                jdcFechaTerminoEd.setDate(fechaDate);
            } catch (ParseException ex) {
                //System.out.println("Fecha en formato incorrecto!");
                Logger.getLogger(FrmCliente.class.getName()).log(Level.SEVERE, null, ex);
            }

            //========================================
            // Tratamiento de atributo UNIDAD            
            String idUnidadString = vector[4];
            String[] vectorUnidad = new String[2];
            int idUnidadInt = Integer.parseInt(idUnidadString);
            vectorUnidad = unidadBO.buscarUnidad(idUnidadInt);
            String unidadNombre = vectorUnidad[1];
            cmbUnidadEd.setSelectedItem(unidadNombre);

            //========================================
            //========================================
            // Tratamiento de atributo ESTADO
            String idEstadoString = vector[5];
            String[] vectorEstado = new String[2];
            int idEstadoInt = Integer.parseInt(idEstadoString);
            vectorEstado = estadoBO.buscarEstado(idEstadoInt);
            String estadoDescripcion = vectorEstado[1];
            cmbEstadoEd.setSelectedItem(estadoDescripcion);

            //========================================
            // Tratamiento de atributo USUARIO            
            String idUsuarioString = vector[6];
            String[] vectorUsuario = new String[2];
            int idUsuarioInt = Integer.parseInt(idUsuarioString);
            vectorUsuario = usuarioBO.buscarUsuario(idUsuarioInt);
            String usuarioNombre = vectorUsuario[1];
            cmbUsuarioEd.setSelectedItem(usuarioNombre);

            // Tratamiento de atributo proceso            
            //String idproceso = vector[7];

            //idProcesoInt = Integer.parseInt(idproceso);

        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    // 01-12-2020
    // AGREGAR NUEVA FUNCION
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        //Captura y asignación
        String nombre = txtNombre.getText();
        String unidadString = cmbUnidad.getSelectedItem().toString();
        String estadoString = cmbEstado.getSelectedItem().toString();
        String usuarioString = cmbUsuario.getSelectedItem().toString();
//        String procesoString = cmbProceso.getSelectedItem().toString();

        int unidadIndex = cmbUnidad.getSelectedIndex();
        int usuarioIndex = cmbUsuario.getSelectedIndex();
        int estadoIndex = cmbEstado.getSelectedIndex();
//        int procesoIndex = cmbProceso.getSelectedIndex();

        if (validacionAgregar(nombre, unidadString, estadoString, usuarioString) == true) {

            SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-YYYY");
            SimpleDateFormat dFormat2 = new SimpleDateFormat("dd-MM-YYYY");
            String fechaInicio = dFormat.format(jdcFechaInicio.getDate());
            String fechaTermino = dFormat2.format(jdcFechaTermino.getDate());

            // Instanciación y Asignación
            //Funcion funcion = new Funcion();                
            funcion.setNombre(nombre);
            funcion.setFechaInicio(fechaInicio);
            funcion.setFechaTermino(fechaTermino);
            funcion.setUnidadIdUnidad(unidadIndex);
            funcion.setEstadoIdEstado(estadoIndex);
            funcion.setUsuarioIdUsuario(usuarioIndex);
//                funcion.setProcesoIdProceso(procesoIndex);

            String mensaje = funcionBO.agregarFuncion(funcion);
            JOptionPane.showMessageDialog(null, mensaje, "Infomación", JOptionPane.INFORMATION_MESSAGE);
            //System.out.println("Mensaje: \n" + mensaje);
            limpiarCampos();
            //listarUsuarios();
            listarFuncion();

        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        /*if (this.jTabbedPane1.getSelectedIndex() == 1) {
            System.out.println("Ingreso a pestaña 2");
            listarFuncion();
        }*/
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        listarFuncion();
    }//GEN-LAST:event_btnListarActionPerformed

    //ELIMINAR FUNCION
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String idFuncionString = txtIdFuncionBuscar.getText();

        if (validacionIdFuncion(idFuncionString) == true) {
            //FuncionBO funcionBO = new FuncionBO();
            int idFuncionInt = Integer.parseInt(txtIdFuncionBuscar.getText());

            //Mensaje de Verificación
            int respuesta = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar al Función?", "Confirmación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

            // 0 = Si
            if (respuesta == 0) {
                String mensaje = funcionBO.eliminarFuncion(idFuncionInt);
                /*System.out.println("\n\n***********************************");
                System.out.println("Mensaje Eliminar funcion: " + mensaje);
                System.out.println("\n\n***********************************");*/
                JOptionPane.showMessageDialog(null, mensaje);
                limpiarCamposEd();
                listarFuncion();
            } else {
                JOptionPane.showMessageDialog(null, "Eliminación cancelada!", "Infomación", JOptionPane.INFORMATION_MESSAGE);
            }
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimipiarEdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimipiarEdActionPerformed
        limpiarCamposEd();
    }//GEN-LAST:event_btnLimipiarEdActionPerformed

    /**
     * BOTON EDITAR
     */
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        //Captura y Asignación de campos
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-YYYY");

        String idFuncion = txtIdFuncionBuscar.getText();
        String nombreEd = txtNombreEd.getText();

        String unidadStringEd = cmbUnidadEd.getSelectedItem().toString();
        String estadoStringEd = cmbEstadoEd.getSelectedItem().toString();
        String usuarioStringEd = cmbUsuarioEd.getSelectedItem().toString();
//        String procesoStringEd = cmbProcesoEd.getSelectedItem().toString();

        int estadoIndexEd = cmbEstadoEd.getSelectedIndex();
        int unidadIndexEd = cmbUnidadEd.getSelectedIndex();
        int usuarioIndexEd = cmbUsuarioEd.getSelectedIndex();
//        int procesoIndexEd = cmbProcesoEd.getSelectedIndex();

        //Validación de campos
        if (validacionEdicion(nombreEd, unidadStringEd, estadoStringEd, usuarioStringEd) == true) {

            //Conversion de dato tipo String a int
            int idFuncionInt = Integer.parseInt(idFuncion);

            String fechaInicioEd = dFormat.format(jdcFechaInicioEd.getDate());
            String fechaTerminoEd = dFormat.format(jdcFechaTerminoEd.getDate());

            //Instanciación y Asignación de valores capturados
            //Funcion funcion = new Funcion();
            funcion.setIdFuncion(idFuncionInt);
            funcion.setNombre(nombreEd);
            funcion.setFechaInicio(fechaInicioEd);
            funcion.setFechaTermino(fechaTerminoEd);
            funcion.setUnidadIdUnidad(unidadIndexEd);
            funcion.setEstadoIdEstado(estadoIndexEd);
            funcion.setUsuarioIdUsuario(usuarioIndexEd);
            //funcion.setProcesoIdProceso(idProcesoInt);

            String mensaje = funcionBO.modificarFuncion(funcion);

            //System.out.println("Mensaje: \n" + mensaje);
            JOptionPane.showMessageDialog(null, mensaje, "Infomación", JOptionPane.INFORMATION_MESSAGE);

            limpiarCamposEd();
            listarFuncion();

        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new FrmPanelGeneral().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    // Validación de idFuncion
    private boolean validacionIdFuncion(String idFuncionString) {

        //Validar que el campo de busqueda no esté vacío
        if (Validar.campoVacio(idFuncionString) == false) {
            mostrarMensaje("Error: \nEl campo está vacío! \nDebe completar el campo.");
            txtIdFuncionBuscar.grabFocus();
            limpiarCampos();
            return false;
        }

        //Validar que el campo de busqueda sea numérico
        if (Validar.numeroEntero(idFuncionString) == false) {
            mostrarMensaje("Error: \nEl dato ingresado debe ser numérico!");
            txtIdFuncionBuscar.grabFocus();
            limpiarCampos();
            return false;
        }

        //Validar que idFuncion exista
        //FuncionBO funcionBO = new FuncionBO();
        int idFuncionInt = Integer.parseInt(idFuncionString);
        String[] vector = new String[6];
        vector = funcionBO.buscarFuncion(idFuncionInt);
        String idFuncion = vector[0];

        if (idFuncion == "") {
            mostrarMensaje("Error: \nEl id ingresado no existe!");
            txtIdFuncionBuscar.grabFocus();
            limpiarCampos();
            return false;
        }
        return true;
    }

    // Limpiar campos de pestaña de agregar
    public void limpiarCampos() {
        txtNombre.setText("");
        jdcFechaInicio.setCalendar(null);
        jdcFechaTermino.setCalendar(null);
        cmbUnidad.setSelectedItem("Seleccione");
        cmbEstado.setSelectedItem("Seleccione");
        cmbUsuario.setSelectedItem("Seleccione");
//      cmbProceso.setSelectedItem("Seleccione");

    }

    //Limpiar campos de pestaña de editar
    public void limpiarCamposEd() {
        txtNombreEd.setText("");
        jdcFechaInicioEd.setCalendar(null);
        jdcFechaTerminoEd.setCalendar(null);
        cmbUnidadEd.setSelectedItem("Seleccione");
        cmbEstadoEd.setSelectedItem("Seleccione");
        cmbUsuarioEd.setSelectedItem("Seleccione");
//      cmbProcesoEd.setSelectedItem("Seleccione");

        // (10-12-2020) (Emilio) (Limpieza y habilitación de campo de busqueda)
        txtIdFuncionBuscar.setText("");
        txtIdFuncionBuscar.setEnabled(true);
    }

    // 05-10-2020
    // Método de validación de campos
    // El método usa la clase Validar.java Ruta: com.admintaskv2.cl.test.Validar
    private boolean validacionAgregar(String nombre, String unidadString, String estadoString, String usuarioString) {

        //Validar campos vacíos
        if (Validar.campoVacio(nombre) == false) {
            mostrarMensaje("Error: \nEl nombre está vacío! \nDebe completar el campo.");
            txtNombre.grabFocus(); //Dar el enfoque al control
            return false;
        }

        if (jdcFechaInicio.getDate() == null) {
            mostrarMensaje("Error: \nLa fecha está vacía! \nDebe completar el campo.");
            jdcFechaInicio.grabFocus(); //Dar el enfoque al control
            return false;
        }

        if (jdcFechaTermino.getDate() == null) {
            mostrarMensaje("Error: \nLa fecha está vacía! \nDebe completar el campo.");
            jdcFechaTermino.grabFocus(); //Dar el enfoque al control
            return false;
        }

        if (jdcFechaInicio.getDate().after(jdcFechaTermino.getDate())) {
            mostrarMensaje("Error: \nLa fecha de inicio no puede ser después de la fecha de término!.");
            jdcFechaInicio.grabFocus(); //Dar el enfoque al control
            return false;
        }

        if (Validar.campoVacio(unidadString) == false || unidadString.equals("Seleccione")) {
            mostrarMensaje("Error: \nLa unidad está vacía!");
            cmbUnidad.grabFocus();
            return false;
        }

        if (Validar.campoVacio(estadoString) == false || estadoString.equals("Seleccione")) {
            mostrarMensaje("Error: \nEl estado está vacío!");
            cmbEstado.grabFocus();
            return false;
        }

        if (Validar.campoVacio(usuarioString) == false || usuarioString.equals("Seleccione")) {
            mostrarMensaje("Error: \nEl usuario está vacío!");
            cmbUsuario.grabFocus();
            return false;
        }

//        if (Validar.campoVacio(procesoString) == false) {
//            mostrarMensaje("Error: \nEl proceso está vacío!");
//            cmbProceso.grabFocus();
//            return false;
//        }
        return true;
    }

    private boolean validacionEdicion(String nombreEd, String unidadStringEd, String estadoStringEd, String usuarioStringEd) {

        //Validar campos vacíos
        if (Validar.campoVacio(nombreEd) == false) {
            mostrarMensaje("Error: \nEl nombre está vacío! \nDebe completar el campo.");
            txtNombreEd.grabFocus(); //Dar el enfoque al control
            return false;
        }

        if (jdcFechaInicioEd.getDate() == null) {
            mostrarMensaje("Error: \nLa fecha está vacía! \nDebe completar el campo.");
            jdcFechaInicioEd.grabFocus(); //Dar el enfoque al control
            return false;
        }

        if (jdcFechaTerminoEd.getDate() == null) {
            mostrarMensaje("Error: \nLa fecha está vacía! \nDebe completar el campo.");
            jdcFechaTerminoEd.grabFocus(); //Dar el enfoque al control
            return false;
        }

        if (jdcFechaInicioEd.getDate().after(jdcFechaTerminoEd.getDate())) {
            mostrarMensaje("Error: \nLa fecha de inicio no puede ser después de la fecha de término!.");
            jdcFechaInicioEd.grabFocus(); //Dar el enfoque al control
            return false;
        }

        if (Validar.campoVacio(unidadStringEd) == false || unidadStringEd.equals("Seleccione")) {
            mostrarMensaje("Error: \nLa unidad está vacía!");
            cmbUnidadEd.grabFocus();
            return false;
        }

        if (Validar.campoVacio(estadoStringEd) == false || estadoStringEd.equals("Seleccione")) {
            mostrarMensaje("Error: \nEl estado está vacío!");
            cmbEstadoEd.grabFocus();
            return false;
        }

        if (Validar.campoVacio(usuarioStringEd) == false || usuarioStringEd.equals("Seleccione")) {
            mostrarMensaje("Error: \nEl usuario está vacío!");
            cmbUsuarioEd.grabFocus();
            return false;
        }

//        if (Validar.campoVacio(procesoStringEd) == false) {
//            mostrarMensaje("Error: \nEl proceso está vacío!");
//            cmbProcesoEd.grabFocus();
//            return false;
//        }
        return true;
    }

    //Método común para mostrar mensajes
    private void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje);
    }

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
    public void frmFuncion() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFuncion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFuncion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFuncion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFuncion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFuncion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimipiarEd;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbEstadoEd;
    private javax.swing.JComboBox<String> cmbUnidad;
    private javax.swing.JComboBox<String> cmbUnidadEd;
    private javax.swing.JComboBox<String> cmbUsuario;
    private javax.swing.JComboBox<String> cmbUsuarioEd;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.toedter.calendar.JDateChooser jdcFechaInicio;
    private com.toedter.calendar.JDateChooser jdcFechaInicioEd;
    private com.toedter.calendar.JDateChooser jdcFechaTermino;
    private com.toedter.calendar.JDateChooser jdcFechaTerminoEd;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEstadoEd;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblFechaInicioEd;
    private javax.swing.JLabel lblFechaTermino;
    private javax.swing.JLabel lblFechaTerminoEd;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblUnidad;
    private javax.swing.JLabel lblUnidadEd;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuarioEd;
    private javax.swing.JTable tblFuncion;
    private javax.swing.JTextField txtIdFuncionBuscar;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreEd;
    // End of variables declaration//GEN-END:variables
}
