package view;

import bo.UsuarioBO;
import dao.UsuarioDAO;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Label;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 * 30-09-2020
 *
 * @author Emilio
 */
public class FrmPanelGeneral extends javax.swing.JFrame {

    //String rutUsuario = "";    
    //String nombre = "";
    //String apellido_paterno = "";
    //String apellido_materno = "";
    private UsuarioBO usuarioBO = new UsuarioBO();
    private UsuarioDAO usuarioDAO = new UsuarioDAO();

    /* 16-12-2020
     * @author Emilio
     * @throws Cargar nombre de usuario en el panel de control
     */
    public String cargarNombreUsuario() {
        String rutUsuario = FrmLogin.rutLogin;
        String datos = "";
        String[] vector = new String[3];
        vector = usuarioBO.buscarUsuarioPorRut(rutUsuario);
        String nombre = vector[0];
        String apellido_paterno = vector[1];
        String apellido_materno = vector[2];
        datos = (nombre + " " + apellido_paterno + " " + apellido_materno);
        //System.out.println("nombreCompleto: " + datos);
        //lblNombreUsuarioPanel.setText(nombreCompleto);
        return datos;
    }

    public FrmPanelGeneral() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Panel General - Sistema Admintask");
        setResizable(true);

        //Integración de icono en la ventana de titulo de la ventana
        BufferedImage image = null;
        try {
            image = ImageIO.read(new File("src/icons/icons32px/logo30px.png"));
        } catch (IOException ex) {
            Logger.getLogger(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        setIconImage(image);

        //(16-12-2020) (Emilio) Mostrar nombre de usuario
        String rutCapturado = FrmLogin.rutLogin;
        //System.out.println("rutCapturado: "+rutCapturado);
        String[] vector = new String[3];
        vector = usuarioBO.buscarUsuarioPorRut(rutCapturado);
        String nombre = vector[0];
        String apellido_paterno = vector[1];
        String apellido_materno = vector[2];
        String nombreRetornado = (nombre + " " + apellido_paterno + " " + apellido_materno);
        //System.out.println("nombreRetornado: " + nombreRetornado);
        lblNombreUsuarioPanel.setText(nombreRetornado);
    }

    public void abrirInternet() {
        try {
            Desktop.getDesktop().browse(URI.create("www.google.cl"));
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panTitulo = new javax.swing.JPanel();
        lblTituloPanel = new javax.swing.JLabel();
        lblCalculadora = new javax.swing.JLabel();
        lblInternet = new javax.swing.JLabel();
        lblSalir = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblNombreUsuarioPanel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        panClientes = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panEstados = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panFunciones = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panProcesos = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panReportes = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        panRoles = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        panTareas = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        panUnidades = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        panUsuarios = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        panInfo = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuClientes = new javax.swing.JMenu();
        mniClientes = new javax.swing.JMenuItem();
        mnuEstados = new javax.swing.JMenu();
        mniEstados = new javax.swing.JMenuItem();
        mnuFunciones = new javax.swing.JMenu();
        mniFunciones = new javax.swing.JMenuItem();
        mnuProcesos = new javax.swing.JMenu();
        mniProcesos = new javax.swing.JMenuItem();
        mnuReportes = new javax.swing.JMenu();
        mniReportes = new javax.swing.JMenuItem();
        mnuRoles = new javax.swing.JMenu();
        mniRoles = new javax.swing.JMenuItem();
        mnuTareas = new javax.swing.JMenu();
        mniTareas = new javax.swing.JMenuItem();
        mnuUnidades = new javax.swing.JMenu();
        mniUnidades = new javax.swing.JMenuItem();
        mnuUsuarios = new javax.swing.JMenu();
        mnisuarios = new javax.swing.JMenuItem();
        mnuInfo = new javax.swing.JMenu();
        mniAcerca = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenu();
        mniSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 740));
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 740));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1110, 720));

        panTitulo.setBackground(new java.awt.Color(55, 68, 140));

        lblTituloPanel.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        lblTituloPanel.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloPanel.setText("Panel General Admintask");

        lblCalculadora.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblCalculadora.setForeground(new java.awt.Color(255, 255, 255));
        lblCalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/calculadora.png"))); // NOI18N
        lblCalculadora.setText("Calculadora");
        lblCalculadora.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCalculadora.setMaximumSize(new java.awt.Dimension(72, 72));
        lblCalculadora.setMinimumSize(new java.awt.Dimension(72, 72));
        lblCalculadora.setPreferredSize(new java.awt.Dimension(72, 72));
        lblCalculadora.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblCalculadora.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblCalculadoraMouseMoved(evt);
            }
        });
        lblCalculadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCalculadoraMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCalculadoraMouseExited(evt);
            }
        });

        lblInternet.setBackground(new java.awt.Color(255, 255, 255));
        lblInternet.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblInternet.setForeground(new java.awt.Color(255, 255, 255));
        lblInternet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInternet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/globo.png"))); // NOI18N
        lblInternet.setText("Internet");
        lblInternet.setToolTipText("");
        lblInternet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblInternet.setMaximumSize(new java.awt.Dimension(72, 72));
        lblInternet.setMinimumSize(new java.awt.Dimension(72, 72));
        lblInternet.setPreferredSize(new java.awt.Dimension(72, 72));
        lblInternet.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblInternet.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblInternetMouseMoved(evt);
            }
        });
        lblInternet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInternetMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblInternetMouseExited(evt);
            }
        });

        lblSalir.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblSalir.setForeground(new java.awt.Color(255, 255, 255));
        lblSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/apagar.png"))); // NOI18N
        lblSalir.setText("Salir");
        lblSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSalir.setMaximumSize(new java.awt.Dimension(72, 72));
        lblSalir.setMinimumSize(new java.awt.Dimension(72, 72));
        lblSalir.setPreferredSize(new java.awt.Dimension(72, 72));
        lblSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblSalir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblSalirMouseMoved(evt);
            }
        });
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSalirMouseExited(evt);
            }
        });

        lblLogout.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 255, 255));
        lblLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/logout32px.png"))); // NOI18N
        lblLogout.setText("Logout");
        lblLogout.setToolTipText("");
        lblLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblLogout.setMaximumSize(new java.awt.Dimension(72, 72));
        lblLogout.setMinimumSize(new java.awt.Dimension(72, 72));
        lblLogout.setPreferredSize(new java.awt.Dimension(72, 72));
        lblLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblLogout.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblLogoutMouseMoved(evt);
            }
        });
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogoutMouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/logo30px.png"))); // NOI18N

        lblNombreUsuarioPanel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNombreUsuarioPanel.setForeground(new java.awt.Color(255, 255, 204));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Bienvenido usuario: ");

        javax.swing.GroupLayout panTituloLayout = new javax.swing.GroupLayout(panTitulo);
        panTitulo.setLayout(panTituloLayout);
        panTituloLayout.setHorizontalGroup(
            panTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTituloLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloPanel)
                    .addGroup(panTituloLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNombreUsuarioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCalculadora, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(lblInternet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(lblLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(lblSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        panTituloLayout.setVerticalGroup(
            panTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTituloLayout.createSequentialGroup()
                .addGroup(panTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panTituloLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(panTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCalculadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInternet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panTituloLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(panTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTituloPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(lblNombreUsuarioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panClientes.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        panClientes.setMaximumSize(new java.awt.Dimension(120, 120));
        panClientes.setMinimumSize(new java.awt.Dimension(120, 120));
        panClientes.setPreferredSize(new java.awt.Dimension(120, 120));
        panClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panClientesMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(55, 68, 140));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons64px/clientes.png"))); // NOI18N
        jLabel2.setText("Clientes");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout panClientesLayout = new javax.swing.GroupLayout(panClientes);
        panClientes.setLayout(panClientesLayout);
        panClientesLayout.setHorizontalGroup(
            panClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panClientesLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panClientesLayout.setVerticalGroup(
            panClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panClientesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panEstados.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        panEstados.setMaximumSize(new java.awt.Dimension(120, 120));
        panEstados.setMinimumSize(new java.awt.Dimension(120, 120));
        panEstados.setPreferredSize(new java.awt.Dimension(120, 120));
        panEstados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panEstadosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panEstadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panEstadosMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(55, 68, 140));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons64px/estados.png"))); // NOI18N
        jLabel3.setText("Estados");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout panEstadosLayout = new javax.swing.GroupLayout(panEstados);
        panEstados.setLayout(panEstadosLayout);
        panEstadosLayout.setHorizontalGroup(
            panEstadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEstadosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panEstadosLayout.setVerticalGroup(
            panEstadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEstadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );

        panFunciones.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        panFunciones.setMaximumSize(new java.awt.Dimension(120, 120));
        panFunciones.setMinimumSize(new java.awt.Dimension(120, 120));
        panFunciones.setPreferredSize(new java.awt.Dimension(120, 120));
        panFunciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panFuncionesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panFuncionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panFuncionesMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(55, 68, 140));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons64px/funciones.png"))); // NOI18N
        jLabel4.setText("Funciones");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout panFuncionesLayout = new javax.swing.GroupLayout(panFunciones);
        panFunciones.setLayout(panFuncionesLayout);
        panFuncionesLayout.setHorizontalGroup(
            panFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panFuncionesLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(24, 24, 24))
        );
        panFuncionesLayout.setVerticalGroup(
            panFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panFuncionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );

        panProcesos.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        panProcesos.setMaximumSize(new java.awt.Dimension(120, 120));
        panProcesos.setMinimumSize(new java.awt.Dimension(120, 120));
        panProcesos.setPreferredSize(new java.awt.Dimension(120, 120));
        panProcesos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panProcesosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panProcesosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panProcesosMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(55, 68, 140));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons64px/procesos.png"))); // NOI18N
        jLabel5.setText("Procesos");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout panProcesosLayout = new javax.swing.GroupLayout(panProcesos);
        panProcesos.setLayout(panProcesosLayout);
        panProcesosLayout.setHorizontalGroup(
            panProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panProcesosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        panProcesosLayout.setVerticalGroup(
            panProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panProcesosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panReportes.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        panReportes.setMaximumSize(new java.awt.Dimension(120, 120));
        panReportes.setMinimumSize(new java.awt.Dimension(120, 120));
        panReportes.setPreferredSize(new java.awt.Dimension(120, 120));
        panReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panReportesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panReportesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panReportesMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(55, 68, 140));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons64px/reportes.png"))); // NOI18N
        jLabel6.setText("Reportes");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout panReportesLayout = new javax.swing.GroupLayout(panReportes);
        panReportes.setLayout(panReportesLayout);
        panReportesLayout.setHorizontalGroup(
            panReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panReportesLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(27, 27, 27))
        );
        panReportesLayout.setVerticalGroup(
            panReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panReportesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );

        panRoles.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        panRoles.setMaximumSize(new java.awt.Dimension(120, 120));
        panRoles.setMinimumSize(new java.awt.Dimension(120, 120));
        panRoles.setPreferredSize(new java.awt.Dimension(120, 120));
        panRoles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panRolesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panRolesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panRolesMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(55, 68, 140));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons64px/roles.png"))); // NOI18N
        jLabel7.setText("Roles");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout panRolesLayout = new javax.swing.GroupLayout(panRoles);
        panRoles.setLayout(panRolesLayout);
        panRolesLayout.setHorizontalGroup(
            panRolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRolesLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        panRolesLayout.setVerticalGroup(
            panRolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRolesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panTareas.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        panTareas.setMaximumSize(new java.awt.Dimension(120, 120));
        panTareas.setMinimumSize(new java.awt.Dimension(120, 120));
        panTareas.setPreferredSize(new java.awt.Dimension(120, 120));
        panTareas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panTareasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panTareasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panTareasMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(55, 68, 140));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons64px/tareas.png"))); // NOI18N
        jLabel8.setText("Tareas");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout panTareasLayout = new javax.swing.GroupLayout(panTareas);
        panTareas.setLayout(panTareasLayout);
        panTareasLayout.setHorizontalGroup(
            panTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTareasLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(26, 26, 26))
        );
        panTareasLayout.setVerticalGroup(
            panTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTareasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );

        panUnidades.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        panUnidades.setMaximumSize(new java.awt.Dimension(120, 120));
        panUnidades.setMinimumSize(new java.awt.Dimension(120, 120));
        panUnidades.setPreferredSize(new java.awt.Dimension(120, 120));
        panUnidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panUnidadesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panUnidadesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panUnidadesMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(55, 68, 140));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons64px/unidades.png"))); // NOI18N
        jLabel9.setText("Unidades");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout panUnidadesLayout = new javax.swing.GroupLayout(panUnidades);
        panUnidades.setLayout(panUnidadesLayout);
        panUnidadesLayout.setHorizontalGroup(
            panUnidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panUnidadesLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(26, 26, 26))
        );
        panUnidadesLayout.setVerticalGroup(
            panUnidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panUnidadesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panUsuarios.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        panUsuarios.setMaximumSize(new java.awt.Dimension(120, 120));
        panUsuarios.setMinimumSize(new java.awt.Dimension(120, 120));
        panUsuarios.setPreferredSize(new java.awt.Dimension(120, 120));
        panUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panUsuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panUsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panUsuariosMouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(55, 68, 140));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons64px/usuarios.png"))); // NOI18N
        jLabel10.setText("Usuarios");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout panUsuariosLayout = new javax.swing.GroupLayout(panUsuarios);
        panUsuarios.setLayout(panUsuariosLayout);
        panUsuariosLayout.setHorizontalGroup(
            panUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panUsuariosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel10)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panUsuariosLayout.setVerticalGroup(
            panUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panInfo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        panInfo.setMaximumSize(new java.awt.Dimension(120, 120));
        panInfo.setMinimumSize(new java.awt.Dimension(120, 120));
        panInfo.setPreferredSize(new java.awt.Dimension(120, 120));
        panInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panInfoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panInfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panInfoMouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(55, 68, 140));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons64px/info.png"))); // NOI18N
        jLabel11.setText("Info");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout panInfoLayout = new javax.swing.GroupLayout(panInfo);
        panInfo.setLayout(panInfoLayout);
        panInfoLayout.setHorizontalGroup(
            panInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInfoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel11)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panInfoLayout.setVerticalGroup(
            panInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(219, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panRoles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panTareas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panEstados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panUnidades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panFunciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(panUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(panProcesos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(265, Short.MAX_VALUE))
            .addComponent(panTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(panReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panProcesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panFunciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(panInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panTareas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panRoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(134, Short.MAX_VALUE))
        );

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mnuClientes.setText("Clientes");
        mnuClientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mniClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        mniClientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mniClientes.setText("Gestión de Clientes");
        mniClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniClientesActionPerformed(evt);
            }
        });
        mnuClientes.add(mniClientes);

        jMenuBar1.add(mnuClientes);

        mnuEstados.setText("Estados");
        mnuEstados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mniEstados.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        mniEstados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mniEstados.setText("Gestión de Estados");
        mniEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEstadosActionPerformed(evt);
            }
        });
        mnuEstados.add(mniEstados);

        jMenuBar1.add(mnuEstados);

        mnuFunciones.setText("Funciones");
        mnuFunciones.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mniFunciones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        mniFunciones.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mniFunciones.setText("Gestión de Funciones");
        mniFunciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniFuncionesActionPerformed(evt);
            }
        });
        mnuFunciones.add(mniFunciones);

        jMenuBar1.add(mnuFunciones);

        mnuProcesos.setText("Procesos");
        mnuProcesos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mniProcesos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        mniProcesos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mniProcesos.setText("Gestión de Procesos");
        mniProcesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniProcesosActionPerformed(evt);
            }
        });
        mnuProcesos.add(mniProcesos);

        jMenuBar1.add(mnuProcesos);

        mnuReportes.setText("Reportes");
        mnuReportes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mniReportes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mniReportes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mniReportes.setText("Gestión de Reportes");
        mniReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniReportesActionPerformed(evt);
            }
        });
        mnuReportes.add(mniReportes);

        jMenuBar1.add(mnuReportes);

        mnuRoles.setText("Roles");
        mnuRoles.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mniRoles.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        mniRoles.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mniRoles.setText("Gestión de Roles");
        mniRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniRolesActionPerformed(evt);
            }
        });
        mnuRoles.add(mniRoles);

        jMenuBar1.add(mnuRoles);

        mnuTareas.setText("Tareas");
        mnuTareas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mniTareas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK));
        mniTareas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mniTareas.setText("Gestión de Tareas");
        mniTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTareasActionPerformed(evt);
            }
        });
        mnuTareas.add(mniTareas);

        jMenuBar1.add(mnuTareas);

        mnuUnidades.setText("Unidades");
        mnuUnidades.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mniUnidades.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        mniUnidades.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mniUnidades.setText("Gestión de Unidades");
        mniUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniUnidadesActionPerformed(evt);
            }
        });
        mnuUnidades.add(mniUnidades);

        jMenuBar1.add(mnuUnidades);

        mnuUsuarios.setText("Usuarios");
        mnuUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mnisuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnisuarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnisuarios.setText("Gestión de Usuarios");
        mnisuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnisuariosActionPerformed(evt);
            }
        });
        mnuUsuarios.add(mnisuarios);

        jMenuBar1.add(mnuUsuarios);

        mnuInfo.setText("Info");
        mnuInfo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mniAcerca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK));
        mniAcerca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mniAcerca.setText("Acerca del Sistema");
        mniAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAcercaActionPerformed(evt);
            }
        });
        mnuInfo.add(mniAcerca);

        jMenuBar1.add(mnuInfo);

        mnuSalir.setText("Salir");
        mnuSalir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mniSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        mniSalir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mniSalir.setText("Salir del Sistema");
        mniSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSalirActionPerformed(evt);
            }
        });
        mnuSalir.add(mniSalir);

        jMenuBar1.add(mnuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1412, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mniSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSalirActionPerformed
        JOptionPane.showMessageDialog(null, "Cerrando Sistema!", "Aviso de Cierre", JOptionPane.INFORMATION_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_mniSalirActionPerformed

    private void mniClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniClientesActionPerformed
        FrmCliente frmCliente = new FrmCliente();
        frmCliente.frmCliente();
        this.setVisible(false);
    }//GEN-LAST:event_mniClientesActionPerformed

    private void mniEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEstadosActionPerformed
        FrmEstado frmEstado = new FrmEstado();
        frmEstado.frmEstado();
        this.setVisible(false);
    }//GEN-LAST:event_mniEstadosActionPerformed

    private void mniRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniRolesActionPerformed
        FrmRol frmRol = new FrmRol();
        frmRol.frmRol();
        this.setVisible(false);
    }//GEN-LAST:event_mniRolesActionPerformed

    private void mnisuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnisuariosActionPerformed
        FrmUsuario frmUsuario = new FrmUsuario();
        frmUsuario.frmUsuario();
        this.setVisible(false);
    }//GEN-LAST:event_mnisuariosActionPerformed

    private void lblSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseExited
        lblSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(55, 68, 140)));
    }//GEN-LAST:event_lblSalirMouseExited

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        //JOptionPane.showMessageDialog(null, "Cerrando Sistema!", "Aviso de Cierre", JOptionPane.INFORMATION_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_lblSalirMouseClicked

    private void lblSalirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseMoved
        lblSalir.setBorder(javax.swing.BorderFactory.createLineBorder(Color.WHITE));
    }//GEN-LAST:event_lblSalirMouseMoved

    private void lblCalculadoraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCalculadoraMouseExited
        lblCalculadora.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(55, 68, 140)));
    }//GEN-LAST:event_lblCalculadoraMouseExited

    private void lblCalculadoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCalculadoraMouseClicked
        try {
            Runtime rtm = Runtime.getRuntime();
            Process process = rtm.exec("calc");
            process.waitFor();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_lblCalculadoraMouseClicked

    private void lblCalculadoraMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCalculadoraMouseMoved
        lblCalculadora.setBorder(javax.swing.BorderFactory.createLineBorder(Color.WHITE));
    }//GEN-LAST:event_lblCalculadoraMouseMoved

    private void lblInternetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInternetMouseExited
        lblInternet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(55, 68, 140)));
    }//GEN-LAST:event_lblInternetMouseExited

    private void lblInternetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInternetMouseClicked
        abrirInternet();
    }//GEN-LAST:event_lblInternetMouseClicked

    private void lblInternetMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInternetMouseMoved
        lblInternet.setBorder(javax.swing.BorderFactory.createLineBorder(Color.WHITE));
    }//GEN-LAST:event_lblInternetMouseMoved

    private void panClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panClientesMouseEntered
        setColor(panClientes);
    }//GEN-LAST:event_panClientesMouseEntered

    private void panClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panClientesMouseExited
        resetColor(panClientes);
    }//GEN-LAST:event_panClientesMouseExited

    private void panEstadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panEstadosMouseEntered
        setColor(panEstados);
    }//GEN-LAST:event_panEstadosMouseEntered

    private void panEstadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panEstadosMouseExited
        resetColor(panEstados);
    }//GEN-LAST:event_panEstadosMouseExited

    private void panFuncionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panFuncionesMouseEntered
        setColor(panFunciones);
    }//GEN-LAST:event_panFuncionesMouseEntered

    private void panFuncionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panFuncionesMouseExited
        resetColor(panFunciones);
    }//GEN-LAST:event_panFuncionesMouseExited

    private void panProcesosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panProcesosMouseEntered
        setColor(panProcesos);
    }//GEN-LAST:event_panProcesosMouseEntered

    private void panProcesosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panProcesosMouseExited
        resetColor(panProcesos);
    }//GEN-LAST:event_panProcesosMouseExited

    private void panReportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panReportesMouseEntered
        setColor(panReportes);
    }//GEN-LAST:event_panReportesMouseEntered

    private void panReportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panReportesMouseExited
        resetColor(panReportes);
    }//GEN-LAST:event_panReportesMouseExited

    private void panRolesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panRolesMouseEntered
        setColor(panRoles);
    }//GEN-LAST:event_panRolesMouseEntered

    private void panRolesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panRolesMouseExited
        resetColor(panRoles);
    }//GEN-LAST:event_panRolesMouseExited

    private void panTareasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panTareasMouseEntered
        setColor(panTareas);
    }//GEN-LAST:event_panTareasMouseEntered

    private void panTareasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panTareasMouseExited
        resetColor(panTareas);
    }//GEN-LAST:event_panTareasMouseExited

    private void panUnidadesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panUnidadesMouseEntered
        setColor(panUnidades);
    }//GEN-LAST:event_panUnidadesMouseEntered

    private void panUnidadesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panUnidadesMouseExited
        resetColor(panUnidades);
    }//GEN-LAST:event_panUnidadesMouseExited

    private void panUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panUsuariosMouseEntered
        setColor(panUsuarios);
    }//GEN-LAST:event_panUsuariosMouseEntered

    private void panUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panUsuariosMouseExited
        resetColor(panUsuarios);
    }//GEN-LAST:event_panUsuariosMouseExited

    private void panInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panInfoMouseEntered
        setColor(panInfo);
    }//GEN-LAST:event_panInfoMouseEntered

    private void panClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panClientesMouseClicked
        FrmCliente frmCliente = new FrmCliente();
        frmCliente.frmCliente();
        this.setVisible(false);
    }//GEN-LAST:event_panClientesMouseClicked

    private void panEstadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panEstadosMouseClicked
        FrmEstado frmEstado = new FrmEstado();
        frmEstado.frmEstado();
        this.setVisible(false);
    }//GEN-LAST:event_panEstadosMouseClicked

    private void panUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panUsuariosMouseClicked
        FrmUsuario frmUsuario = new FrmUsuario();
        frmUsuario.frmUsuario();
        this.setVisible(false);
    }//GEN-LAST:event_panUsuariosMouseClicked

    private void panInfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panInfoMouseExited
        resetColor(panInfo);
    }//GEN-LAST:event_panInfoMouseExited

    private void panRolesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panRolesMouseClicked
        FrmRol frmRol = new FrmRol();
        frmRol.frmRol();
        this.setVisible(false);
    }//GEN-LAST:event_panRolesMouseClicked

    private void lblLogoutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseMoved
        lblLogout.setBorder(javax.swing.BorderFactory.createLineBorder(Color.WHITE));
    }//GEN-LAST:event_lblLogoutMouseMoved

    private void lblLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseExited
        lblLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(55, 68, 140)));
    }//GEN-LAST:event_lblLogoutMouseExited

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        new FrmLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void panProcesosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panProcesosMouseClicked
        new FrmProceso().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panProcesosMouseClicked

    private void panReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panReportesMouseClicked
        new FrmReporte().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panReportesMouseClicked

    private void panFuncionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panFuncionesMouseClicked
        new FrmFuncion().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panFuncionesMouseClicked

    private void panUnidadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panUnidadesMouseClicked
        new FrmUnidad().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panUnidadesMouseClicked

    private void mniProcesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniProcesosActionPerformed
        FrmProceso frmProceso = new FrmProceso();
        frmProceso.frmProceso();
        this.setVisible(false);
    }//GEN-LAST:event_mniProcesosActionPerformed

    private void mniReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniReportesActionPerformed
        FrmReporte frmReporte = new FrmReporte();
        frmReporte.frmReporte();
        this.setVisible(false);
    }//GEN-LAST:event_mniReportesActionPerformed

    private void mniUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniUnidadesActionPerformed
        FrmUnidad frmUnidad = new FrmUnidad();
        frmUnidad.frmUnidad();
        this.setVisible(false);
    }//GEN-LAST:event_mniUnidadesActionPerformed

    private void panInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panInfoMouseClicked
        FrmInfo frmInfo = new FrmInfo();
        frmInfo.frmInfo();
        this.setVisible(false);
    }//GEN-LAST:event_panInfoMouseClicked

    private void panTareasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panTareasMouseClicked
        FrmTarea frmTarea = new FrmTarea();
        frmTarea.frmTarea();
        this.setVisible(false);
    }//GEN-LAST:event_panTareasMouseClicked

    private void mniFuncionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniFuncionesActionPerformed
        FrmFuncion frmFuncion = new FrmFuncion();
        frmFuncion.frmFuncion();
        this.setVisible(false);
    }//GEN-LAST:event_mniFuncionesActionPerformed

    private void mniTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTareasActionPerformed
        FrmTarea frmTarea = new FrmTarea();
        frmTarea.frmTarea();
        this.setVisible(false);
    }//GEN-LAST:event_mniTareasActionPerformed

    private void mniAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAcercaActionPerformed
        FrmInfo frmInfo = new FrmInfo();
        frmInfo.frmInfo();
        this.setVisible(false);
    }//GEN-LAST:event_mniAcercaActionPerformed

    //Método para resaltar el color del panel al posicionar el mouse sobre el
    public void setColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(205, 213, 224));
    }

    //Método para normalizar el color del panel al sacar el mouse
    public void resetColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(240, 240, 240));
    }

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
    public void frmPanelGeneral() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPanelGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPanelGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPanelGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPanelGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPanelGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCalculadora;
    private javax.swing.JLabel lblInternet;
    private javax.swing.JLabel lblLogout;
    public static javax.swing.JLabel lblNombreUsuarioPanel;
    private javax.swing.JLabel lblSalir;
    private javax.swing.JLabel lblTituloPanel;
    private javax.swing.JMenuItem mniAcerca;
    private javax.swing.JMenuItem mniClientes;
    private javax.swing.JMenuItem mniEstados;
    private javax.swing.JMenuItem mniFunciones;
    private javax.swing.JMenuItem mniProcesos;
    private javax.swing.JMenuItem mniReportes;
    private javax.swing.JMenuItem mniRoles;
    private javax.swing.JMenuItem mniSalir;
    private javax.swing.JMenuItem mniTareas;
    private javax.swing.JMenuItem mniUnidades;
    private javax.swing.JMenuItem mnisuarios;
    private javax.swing.JMenu mnuClientes;
    private javax.swing.JMenu mnuEstados;
    private javax.swing.JMenu mnuFunciones;
    private javax.swing.JMenu mnuInfo;
    private javax.swing.JMenu mnuProcesos;
    private javax.swing.JMenu mnuReportes;
    private javax.swing.JMenu mnuRoles;
    private javax.swing.JMenu mnuSalir;
    private javax.swing.JMenu mnuTareas;
    private javax.swing.JMenu mnuUnidades;
    private javax.swing.JMenu mnuUsuarios;
    private javax.swing.JPanel panClientes;
    private javax.swing.JPanel panEstados;
    private javax.swing.JPanel panFunciones;
    private javax.swing.JPanel panInfo;
    private javax.swing.JPanel panProcesos;
    private javax.swing.JPanel panReportes;
    private javax.swing.JPanel panRoles;
    private javax.swing.JPanel panTareas;
    private javax.swing.JPanel panTitulo;
    private javax.swing.JPanel panUnidades;
    private javax.swing.JPanel panUsuarios;
    // End of variables declaration//GEN-END:variables
}
