package view;


import bo.UsuarioBO;
import bo.TareaBO;
import dao.TareaDAO;
import bo.EstadoBO;
import bo.FuncionBO;
import bo.SubTareaBO;
import entity.SubTarea;
import entity.Tarea;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import test.Validar;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;


/**
 *
 * @author Kevin
 */
public class FrmTarea extends javax.swing.JFrame {

    SubTarea subTarea = new SubTarea();
    Tarea tarea = new Tarea();
    private TareaBO tareaBO = new TareaBO();
    private TareaDAO tareaDAO = new TareaDAO();
    
    private UsuarioBO usuarioBO = new UsuarioBO();
    private FuncionBO funcionBO = new FuncionBO();
    private EstadoBO estadoBO = new EstadoBO();
    private SubTareaBO subTareaBO = new SubTareaBO();
    

    public FrmTarea() {
        initComponents();
        jTabbedPane1.setEnabledAt(2, false);
        
        this.setLocationRelativeTo(null);
        setTitle("Módulo - Gestión de Tareas");
        setResizable(false);
        listarTarea();
        listarCliente();
        listarFuncion();
        listarEstado();
        //btnAddSubTarea.setEnabled(false);
        
        //Integración de icono en la ventana de titulo de la ventana
        BufferedImage image = null;
        try {
            image = ImageIO.read(new File("src/icons/icons32px/logo30px.png"));
        } catch (IOException ex) {
            Logger.getLogger(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        setIconImage(image);
    }
    
    public void listarTarea(){
        tareaBO.listarTarea(tblTarea);
    }
    
    public void listarSubTarea(int idTarea){
        subTareaBO.listarSubTarea2(tblSubTarea,idTarea);
    }

    public void listarCliente() {
        usuarioBO.listarUsuarioCmb(cmbEncargado);
        usuarioBO.listarUsuarioCmb(cmbEncargadoEd);
    }
    public void listarFuncion() {
        funcionBO.listarFuncionCmb(cmbFuncion);
        funcionBO.listarFuncionCmb(cmbFuncionEd);
    }
    public void listarEstado(){ 
        estadoBO.listarEstadoCmb(cmbEstado);
        estadoBO.listarEstadoCmb(cmbEstadoEd);
    }    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        btnAgregar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        lblNombre7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jDateFechaInicio = new com.toedter.calendar.JDateChooser();
        jDateFechaTermino = new com.toedter.calendar.JDateChooser();
        cmbEstado = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        lblNombre8 = new javax.swing.JLabel();
        lblUnidadEd1 = new javax.swing.JLabel();
        lblNombre9 = new javax.swing.JLabel();
        lblNombre10 = new javax.swing.JLabel();
        lblNombre11 = new javax.swing.JLabel();
        lblNombre12 = new javax.swing.JLabel();
        cmbFuncion = new javax.swing.JComboBox<>();
        cmbEncargado = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jLabel11 = new javax.swing.JLabel();
        txtIdTareaBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        btnEditar = new javax.swing.JButton();
        btnLimipiarEd = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblNombre1 = new javax.swing.JLabel();
        txtNombreEd = new javax.swing.JTextField();
        lblUnidadEd = new javax.swing.JLabel();
        cmbEncargadoEd = new javax.swing.JComboBox<>();
        lblNombre2 = new javax.swing.JLabel();
        lblNombre3 = new javax.swing.JLabel();
        lblNombre4 = new javax.swing.JLabel();
        lblNombre5 = new javax.swing.JLabel();
        lblNombre6 = new javax.swing.JLabel();
        cmbEstadoEd = new javax.swing.JComboBox<>();
        cmbFuncionEd = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcionEd = new javax.swing.JTextArea();
        jDateFechaInicioEd = new com.toedter.calendar.JDateChooser();
        jDateFechaTerminoEd = new com.toedter.calendar.JDateChooser();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTarea = new javax.swing.JTable();
        btnListar = new javax.swing.JButton();
        btnAddSubTarea = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLayeredPane6 = new javax.swing.JLayeredPane();
        jLabel12 = new javax.swing.JLabel();
        txtIdTareaBuscarSub = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblCantSubTareas = new javax.swing.JLabel();
        lblPorcentajeAvance = new javax.swing.JLabel();
        jLayeredPane7 = new javax.swing.JLayeredPane();
        btnAgregarSubTarea = new javax.swing.JButton();
        btnLimpiarSubTarea = new javax.swing.JButton();
        lblNombre13 = new javax.swing.JLabel();
        txtNombreSub = new javax.swing.JTextField();
        lblNombre18 = new javax.swing.JLabel();
        CBFinalizado = new javax.swing.JCheckBox();
        btnGuardarSubTarea = new javax.swing.JButton();
        btnEliminarSubTarea = new javax.swing.JButton();
        btnListar1 = new javax.swing.JButton();
        jLayeredPane8 = new javax.swing.JLayeredPane();
        jLabel13 = new javax.swing.JLabel();
        txtIdBuscarSubTarea = new javax.swing.JTextField();
        btnBuscarSubTarea = new javax.swing.JButton();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSubTarea = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1948, 800));
        setPreferredSize(new java.awt.Dimension(1948, 800));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1200, 700));
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de la Tarea", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jLayeredPane1.setMaximumSize(new java.awt.Dimension(700, 588));
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(700, 588));

        btnAgregar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/anadir.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.setIconTextGap(20);
        btnAgregar.setPreferredSize(new java.awt.Dimension(100, 25));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/limpiar32px.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setIconTextGap(20);
        btnLimpiar.setPreferredSize(new java.awt.Dimension(100, 25));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lblNombre7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombre7.setText("Nombre:");

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jDateFechaInicio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jDateFechaTermino.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cmbEstado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoActionPerformed(evt);
            }
        });

        txtDescripcion.setColumns(20);
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setRows(5);
        jScrollPane3.setViewportView(txtDescripcion);

        lblNombre8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombre8.setText("Descripción:");

        lblUnidadEd1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUnidadEd1.setText("Encargado:");

        lblNombre9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombre9.setText("Función:");

        lblNombre10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombre10.setText("Estado:");

        lblNombre11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombre11.setText("Fecha Término:");

        lblNombre12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombre12.setText("Fecha Inicio:");

        cmbFuncion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbFuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFuncionActionPerformed(evt);
            }
        });

        cmbEncargado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbEncargado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEncargadoActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(btnAgregar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnLimpiar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblNombre7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jDateFechaInicio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jDateFechaTermino, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cmbEstado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblNombre8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblUnidadEd1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblNombre9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblNombre10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblNombre11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblNombre12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cmbFuncion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cmbEncargado, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre8)
                            .addComponent(lblNombre11)
                            .addComponent(lblNombre12, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombre7)
                            .addComponent(lblNombre10)
                            .addComponent(lblNombre9)
                            .addComponent(lblUnidadEd1))
                        .addGap(72, 72, 72)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNombre)
                                .addComponent(jDateFechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jDateFechaTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre7))
                .addGap(23, 23, 23)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre12)
                    .addComponent(jDateFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre11)
                    .addComponent(jDateFechaTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre10))
                .addGap(23, 23, 23)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre9))
                .addGap(23, 23, 23)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUnidadEd1))
                .addGap(23, 23, 23)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre8)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(665, 665, 665)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(683, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jLayeredPane1.getAccessibleContext().setAccessibleName("Datos del");

        jTabbedPane1.addTab("Agregar Tarea", jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(573, 600));

        jLayeredPane4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Tarea por Id", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jLayeredPane4.setMaximumSize(new java.awt.Dimension(600, 94));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Id Tarea:");

        txtIdTareaBuscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/buscar32px.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setIconTextGap(20);
        btnBuscar.setPreferredSize(new java.awt.Dimension(100, 25));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLayeredPane4.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(txtIdTareaBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(btnBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(27, 27, 27)
                .addComponent(txtIdTareaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtIdTareaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edición de Tarea", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jLayeredPane3.setMaximumSize(new java.awt.Dimension(600, 495));

        btnEditar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/guardar32px.png"))); // NOI18N
        btnEditar.setText("Guardar");
        btnEditar.setIconTextGap(20);
        btnEditar.setPreferredSize(new java.awt.Dimension(100, 25));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnLimipiarEd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLimipiarEd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/limpiar32px.png"))); // NOI18N
        btnLimipiarEd.setText("Limpiar");
        btnLimipiarEd.setIconTextGap(20);
        btnLimipiarEd.setPreferredSize(new java.awt.Dimension(100, 25));
        btnLimipiarEd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimipiarEdActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/eliminar32px.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setIconTextGap(20);
        btnEliminar.setPreferredSize(new java.awt.Dimension(100, 25));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lblNombre1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombre1.setText("Nombre:");

        txtNombreEd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblUnidadEd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUnidadEd.setText("Encargado");

        cmbEncargadoEd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbEncargadoEd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEncargadoEdActionPerformed(evt);
            }
        });

        lblNombre2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombre2.setText("Fecha Inicio:");

        lblNombre3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombre3.setText("Estado:");

        lblNombre4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombre4.setText("Fecha Término:");

        lblNombre5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombre5.setText("Función:");

        lblNombre6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombre6.setText("Descripción:");

        cmbEstadoEd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbEstadoEd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoEdActionPerformed(evt);
            }
        });

        cmbFuncionEd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbFuncionEd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFuncionEdActionPerformed(evt);
            }
        });

        txtDescripcionEd.setColumns(20);
        txtDescripcionEd.setLineWrap(true);
        txtDescripcionEd.setRows(5);
        jScrollPane2.setViewportView(txtDescripcionEd);

        jDateFechaInicioEd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jDateFechaTerminoEd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLayeredPane3.setLayer(btnEditar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(btnLimipiarEd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(btnEliminar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(lblNombre1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(txtNombreEd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(lblUnidadEd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(cmbEncargadoEd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(lblNombre2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(lblNombre3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(lblNombre4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(lblNombre5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(lblNombre6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(cmbEstadoEd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(cmbFuncionEd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jDateFechaInicioEd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jDateFechaTerminoEd, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(btnLimipiarEd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addComponent(lblNombre5)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane3Layout.createSequentialGroup()
                        .addComponent(lblNombre3)
                        .addGap(63, 63, 63))
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUnidadEd)
                            .addComponent(lblNombre6))
                        .addGap(27, 27, 27))
                    .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblNombre1)
                        .addComponent(lblNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNombre4)))
                .addGap(121, 121, 121)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNombreEd)
                        .addComponent(jDateFechaInicioEd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDateFechaTerminoEd, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cmbEncargadoEd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbFuncionEd, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbEstadoEd, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre1)
                    .addComponent(txtNombreEd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre2)
                    .addComponent(jDateFechaInicioEd, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNombre4)
                    .addComponent(jDateFechaTerminoEd, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre3)
                    .addComponent(cmbEstadoEd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre5)
                    .addComponent(cmbFuncionEd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUnidadEd)
                    .addComponent(cmbEncargadoEd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimipiarEd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro de Tareas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jScrollPane1.setBorder(null);

        tblTarea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblTarea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblTarea.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jScrollPane1.setViewportView(tblTarea);

        btnListar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/listar32px.png"))); // NOI18N
        btnListar.setText("Listar");
        btnListar.setIconTextGap(20);
        btnListar.setPreferredSize(new java.awt.Dimension(100, 25));
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnAddSubTarea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddSubTarea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/anadir.png"))); // NOI18N
        btnAddSubTarea.setText("Ver SubTareas");
        btnAddSubTarea.setIconTextGap(20);
        btnAddSubTarea.setPreferredSize(new java.awt.Dimension(100, 25));
        btnAddSubTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSubTareaActionPerformed(evt);
            }
        });

        jLayeredPane2.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(btnListar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(btnAddSubTarea, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1106, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAddSubTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddSubTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayeredPane4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLayeredPane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ver Tareas", jPanel2);

        jLayeredPane6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información de la Tarea", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jLayeredPane6.setMaximumSize(new java.awt.Dimension(600, 94));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Id Tarea:");

        txtIdTareaBuscarSub.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtIdTareaBuscarSub.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Subtareas Asociadas:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("% de Avance:");

        lblCantSubTareas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCantSubTareas.setText("Texto");

        lblPorcentajeAvance.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPorcentajeAvance.setText("Texto");

        jLayeredPane6.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(txtIdTareaBuscarSub, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(lblCantSubTareas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(lblPorcentajeAvance, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane6Layout = new javax.swing.GroupLayout(jLayeredPane6);
        jLayeredPane6.setLayout(jLayeredPane6Layout);
        jLayeredPane6Layout.setHorizontalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(txtIdTareaBuscarSub, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(210, 210, 210)
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane6Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPorcentajeAvance, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane6Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCantSubTareas, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane6Layout.setVerticalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane6Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lblCantSubTareas)
                    .addComponent(jLabel12)
                    .addComponent(txtIdTareaBuscarSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(lblPorcentajeAvance))
                .addGap(32, 32, 32))
        );

        jLayeredPane7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de la Sub Tarea", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jLayeredPane7.setMaximumSize(new java.awt.Dimension(700, 588));
        jLayeredPane7.setPreferredSize(new java.awt.Dimension(700, 588));

        btnAgregarSubTarea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAgregarSubTarea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/anadir.png"))); // NOI18N
        btnAgregarSubTarea.setText("Agregar");
        btnAgregarSubTarea.setIconTextGap(20);
        btnAgregarSubTarea.setPreferredSize(new java.awt.Dimension(100, 25));
        btnAgregarSubTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarSubTareaActionPerformed(evt);
            }
        });

        btnLimpiarSubTarea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLimpiarSubTarea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/limpiar32px.png"))); // NOI18N
        btnLimpiarSubTarea.setText("Limpiar");
        btnLimpiarSubTarea.setIconTextGap(20);
        btnLimpiarSubTarea.setPreferredSize(new java.awt.Dimension(100, 25));
        btnLimpiarSubTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarSubTareaActionPerformed(evt);
            }
        });

        lblNombre13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombre13.setText("Nombre:");

        txtNombreSub.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblNombre18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombre18.setText("Finalizado:");

        btnGuardarSubTarea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnGuardarSubTarea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/guardar32px.png"))); // NOI18N
        btnGuardarSubTarea.setText("Guardar");
        btnGuardarSubTarea.setIconTextGap(20);
        btnGuardarSubTarea.setPreferredSize(new java.awt.Dimension(100, 25));
        btnGuardarSubTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarSubTareaActionPerformed(evt);
            }
        });

        btnEliminarSubTarea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEliminarSubTarea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/eliminar32px.png"))); // NOI18N
        btnEliminarSubTarea.setText("Eliminar");
        btnEliminarSubTarea.setIconTextGap(20);
        btnEliminarSubTarea.setPreferredSize(new java.awt.Dimension(100, 25));
        btnEliminarSubTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarSubTareaActionPerformed(evt);
            }
        });

        jLayeredPane7.setLayer(btnAgregarSubTarea, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane7.setLayer(btnLimpiarSubTarea, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane7.setLayer(lblNombre13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane7.setLayer(txtNombreSub, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane7.setLayer(lblNombre18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane7.setLayer(CBFinalizado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane7.setLayer(btnGuardarSubTarea, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane7.setLayer(btnEliminarSubTarea, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane7Layout = new javax.swing.GroupLayout(jLayeredPane7);
        jLayeredPane7.setLayout(jLayeredPane7Layout);
        jLayeredPane7Layout.setHorizontalGroup(
            jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane7Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane7Layout.createSequentialGroup()
                        .addComponent(lblNombre13)
                        .addGap(301, 301, 301)
                        .addComponent(txtNombreSub, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane7Layout.createSequentialGroup()
                        .addGroup(jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane7Layout.createSequentialGroup()
                                .addComponent(btnEliminarSubTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(108, 108, 108)
                                .addComponent(btnLimpiarSubTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane7Layout.createSequentialGroup()
                                .addComponent(lblNombre18, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(260, 260, 260)
                                .addComponent(CBFinalizado)))
                        .addGap(107, 107, 107)
                        .addGroup(jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardarSubTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarSubTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32))
        );
        jLayeredPane7Layout.setVerticalGroup(
            jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane7Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane7Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblNombre13))
                    .addComponent(txtNombreSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane7Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblNombre18))
                    .addComponent(CBFinalizado))
                .addGap(61, 61, 61)
                .addGroup(jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminarSubTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLimpiarSubTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAgregarSubTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGuardarSubTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69))
        );

        btnListar1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnListar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/listar32px.png"))); // NOI18N
        btnListar1.setText("Listar");
        btnListar1.setIconTextGap(20);
        btnListar1.setPreferredSize(new java.awt.Dimension(100, 25));

        jLayeredPane8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar SubTarea por Id", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jLayeredPane8.setMaximumSize(new java.awt.Dimension(600, 94));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Id SubTarea:");

        txtIdBuscarSubTarea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtIdBuscarSubTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdBuscarSubTareaActionPerformed(evt);
            }
        });

        btnBuscarSubTarea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBuscarSubTarea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/buscar32px.png"))); // NOI18N
        btnBuscarSubTarea.setText("Buscar");
        btnBuscarSubTarea.setIconTextGap(20);
        btnBuscarSubTarea.setPreferredSize(new java.awt.Dimension(100, 25));
        btnBuscarSubTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarSubTareaActionPerformed(evt);
            }
        });

        jLayeredPane8.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane8.setLayer(txtIdBuscarSubTarea, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane8.setLayer(btnBuscarSubTarea, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane8Layout = new javax.swing.GroupLayout(jLayeredPane8);
        jLayeredPane8.setLayout(jLayeredPane8Layout);
        jLayeredPane8Layout.setHorizontalGroup(
            jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane8Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(txtIdBuscarSubTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnBuscarSubTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane8Layout.setVerticalGroup(
            jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane8Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdBuscarSubTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(btnBuscarSubTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLayeredPane5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado SubTareas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        tblSubTarea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tblSubTarea);

        jLayeredPane5.setLayer(jScrollPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane5Layout = new javax.swing.GroupLayout(jLayeredPane5);
        jLayeredPane5.setLayout(jLayeredPane5Layout);
        jLayeredPane5Layout.setHorizontalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane5Layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );
        jLayeredPane5Layout.setVerticalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane5Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
                    .addComponent(jLayeredPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLayeredPane8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(480, 480, 480)
                        .addComponent(btnListar1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLayeredPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLayeredPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLayeredPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnListar1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("SubTareas", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 1938, 704));

        btnVolver.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/volver32px.png"))); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.setIconTextGap(20);
        btnVolver.setPreferredSize(new java.awt.Dimension(100, 25));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 720, 150, 41));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        new FrmPanelGeneral().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

   
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        String idTareaString = txtIdTareaBuscar.getText();
        
        if (validacionIdTarea(idTareaString) == true) {
            
            //btnAddSubTarea.setEnabled(true);
            txtIdTareaBuscar.setEnabled(false);
            String[] vector = new String[8];
            int idTareaInt = Integer.parseInt(txtIdTareaBuscar.getText());
            vector = tareaBO.buscarTarea(idTareaInt);

            txtNombreEd.setText(vector[1]);
            txtDescripcionEd.setText(vector[6]);
            String idUsuarioString = vector[7];
            String idEstadoString = vector[4];
            String idFuncionString = vector[5];
            
            String[] vectorUsuario = new String[2];
            String[] vectorEstado = new String[2];
            String[] vectorFuncion = new String[2];
            
            int idUsuarioInt = Integer.parseInt(idUsuarioString);
            int idEstadoInt = Integer.parseInt(idEstadoString);
            int idFuncionInt = Integer.parseInt(idFuncionString);
            
            vectorFuncion = funcionBO.buscarFuncion(idFuncionInt);
            String FuncionNombre = vectorFuncion[1];
            cmbFuncionEd.setSelectedItem(FuncionNombre); 
            
            vectorUsuario = usuarioBO.buscarUsuario(idUsuarioInt);
            String usuarioNombre = vectorUsuario[1];
            cmbEncargadoEd.setSelectedItem(usuarioNombre); 
            
            vectorEstado = estadoBO.buscarEstado(idEstadoInt);
            String EstadoNombre = vectorEstado[1];
            cmbEstadoEd.setSelectedItem(EstadoNombre); 
            
            try {
                String fechaInicioString = vector[2];
                SimpleDateFormat fechaSimpleDate = new SimpleDateFormat("yyyy-MM-dd");
                Date fechaInicioDate = fechaSimpleDate.parse(fechaInicioString);
                jDateFechaInicioEd.setDate(fechaInicioDate);
                
                String fechaTerminoString = vector[3];
                Date fechaTerminoDate = fechaSimpleDate.parse(fechaTerminoString);
                jDateFechaTerminoEd.setDate(fechaTerminoDate);
                
            } catch (ParseException ex) {
                //System.out.println("Fecha en formato incorrecto!");
                Logger.getLogger(FrmCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            limpiarCampos();
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed


    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        String nombre = txtNombre.getText();
        String descripcion = txtDescripcion.getText();
        String estado = cmbEstado.getSelectedItem().toString();
        String funcion = cmbFuncion.getSelectedItem().toString();
        String usuario = cmbEncargado.getSelectedItem().toString();      
         
        if (validacionAgregar(nombre, estado, funcion, descripcion, usuario) == true) {
            
            int estadoIndex = cmbEstado.getSelectedIndex();
            int funcionIndex = cmbFuncion.getSelectedIndex();
            int encargadoIndex = cmbEncargado.getSelectedIndex();
        
            SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-YYYY");
            String fechaInicio = dFormat.format(jDateFechaInicio.getDate());
            String fechaTermino = dFormat.format(jDateFechaTermino.getDate());
            
            tarea.setNombre(nombre);
            tarea.setDescripcion(descripcion);
            tarea.setFechaInicio(fechaInicio);
            tarea.setFechaTermino(fechaTermino);
            tarea.setEstadoIdEstado(estadoIndex);
            tarea.setFuncionIdFuncion(funcionIndex);
            tarea.setEncargado(encargadoIndex);

            String mensaje = tareaBO.agregarTarea(tarea);
            JOptionPane.showMessageDialog(null, mensaje, "Infomación", JOptionPane.INFORMATION_MESSAGE);
            //System.out.println("Mensaje: \n" + mensaje);
            
            limpiarCampos();
            listarTarea();
        }        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        if (this.jTabbedPane1.getSelectedIndex() == 1) {
            
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        listarTarea();
    }//GEN-LAST:event_btnListarActionPerformed

    
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String idTareaString = txtIdTareaBuscar.getText();
        
        if (validacionIdTarea(idTareaString) == true) {
            int idTareaInt = Integer.parseInt(txtIdTareaBuscar.getText());

            int respuesta = JOptionPane.showConfirmDialog(null, "Podría tener SubTareas Asociadas \n ¿Está seguro de eliminar la Tarea?", "Confirmación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

            if (respuesta == 0) {
                String mensaje = tareaBO.eliminarTarea(idTareaInt);
                JOptionPane.showMessageDialog(null, mensaje);
                limpiarCampos();
                listarTarea();
            } else {
                JOptionPane.showMessageDialog(null, "Eliminación cancelada!", "Infomación", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimipiarEdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimipiarEdActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimipiarEdActionPerformed


    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        
        String idTarea = txtIdTareaBuscar.getText();
        
        String nombreEd = txtNombreEd.getText();
        String descripcionEd = txtDescripcionEd.getText();
        String estadoEd = cmbEstadoEd.getSelectedItem().toString();
        String funcionEd = cmbFuncionEd.getSelectedItem().toString();
        String usuarioEd = cmbEncargadoEd.getSelectedItem().toString();


        if (validacionEdicion(nombreEd,estadoEd, funcionEd, descripcionEd ,usuarioEd) == true) {
            
            int idTareaInt = Integer.parseInt(idTarea);
            int estadoIndex = cmbEstadoEd.getSelectedIndex();
            int funcionIndex = cmbFuncionEd.getSelectedIndex();
            int encargadoIndex = cmbEncargadoEd.getSelectedIndex();
            
            tarea.setIdTarea(idTareaInt);
            tarea.setNombre(nombreEd);
            tarea.setDescripcion(descripcionEd);
            
            SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-YYYY");
            String fechaInicioEd = dFormat.format(jDateFechaInicioEd.getDate());
            String fechaTerminoEd = dFormat.format(jDateFechaTerminoEd.getDate());
            tarea.setFechaInicio(fechaInicioEd);
            tarea.setFechaTermino(fechaTerminoEd);
            
            tarea.setEstadoIdEstado(estadoIndex);
            tarea.setFuncionIdFuncion(funcionIndex);
            tarea.setEncargado(encargadoIndex);

            String mensaje = tareaBO.modificarTarea(tarea);
            JOptionPane.showMessageDialog(null, mensaje, "Infomación", JOptionPane.INFORMATION_MESSAGE);
            //System.out.println("Mensaje: \n" + mensaje);
            
            limpiarCampos();
            listarTarea();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new FrmPanelGeneral().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void cmbEncargadoEdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEncargadoEdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEncargadoEdActionPerformed

    private void cmbEstadoEdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoEdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstadoEdActionPerformed

    private void cmbFuncionEdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFuncionEdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbFuncionEdActionPerformed

    private void cmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstadoActionPerformed

    private void cmbFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFuncionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbFuncionActionPerformed

    private void cmbEncargadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEncargadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEncargadoActionPerformed

    private void btnAgregarSubTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarSubTareaActionPerformed
        String finalizadoSubTarea;        
        String nombreSubTarea = txtNombreSub.getText();
        Boolean estadoSubTarea = CBFinalizado.isSelected();
        int idTarea = Integer.parseInt(txtIdTareaBuscarSub.getText());
        
        if (estadoSubTarea){
            finalizadoSubTarea = "1";
        } else{
            finalizadoSubTarea = "0";
        }

        subTarea.setNombre(nombreSubTarea);
        subTarea.setFinalizado(finalizadoSubTarea);
        subTarea.setTareaIdTarea(idTarea);
        
        String mensaje = subTareaBO.agregarSubTarea(subTarea);
        JOptionPane.showMessageDialog(null, mensaje, "Infomación", JOptionPane.INFORMATION_MESSAGE);
            
        limpiarCampos();
        limpiaCamposSubTarea();
        listarSubTarea(idTarea);
        cargarPorcentajes(idTarea);
    }//GEN-LAST:event_btnAgregarSubTareaActionPerformed

    private void btnLimpiarSubTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarSubTareaActionPerformed
        limpiaCamposSubTarea();
    }//GEN-LAST:event_btnLimpiarSubTareaActionPerformed

    private void cargarPorcentajes(int idTarea){
        String[] vectorP = new String[2];
        vectorP = subTareaBO.buscarPorcentajes(idTarea);
        lblCantSubTareas.setText(vectorP[0]);
        lblPorcentajeAvance.setText(vectorP[1]+" %");
    }
    
    private void btnBuscarSubTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarSubTareaActionPerformed
        String idSubTareaString = txtIdBuscarSubTarea.getText();
        int idTarea = Integer.parseInt(txtIdTareaBuscarSub.getText());
        if (validacionIdSubTarea(idSubTareaString,idTarea) == true){
            txtIdBuscarSubTarea.setEnabled(false);
        
            String[] vector = new String[3];
        
            int idSubTareaInt = Integer.parseInt(txtIdBuscarSubTarea.getText());
            int idTareaInt = Integer.parseInt(txtIdTareaBuscarSub.getText());
            vector = subTareaBO.buscarSubTarea(idSubTareaInt, idTareaInt);        
            if(vector[0] == null){
                limpiaCamposSubTarea();
            }else{
                btnGuardarSubTarea.setVisible(true);
                btnAgregarSubTarea.setVisible(false);
                txtNombreSub.setText(vector[1]);
                if (vector[2].equals("1")){
                    CBFinalizado.setSelected(true);            
                }else{
                    CBFinalizado.setSelected(false);
                }        
                cargarPorcentajes(idTareaInt);
            }
        }   
    }//GEN-LAST:event_btnBuscarSubTareaActionPerformed

    private void btnEliminarSubTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarSubTareaActionPerformed
        String idSubTareaString = txtIdBuscarSubTarea.getText();
        int idTarea = Integer.parseInt(txtIdTareaBuscarSub.getText());
        if (validacionIdSubTarea(idSubTareaString,idTarea) == true) {
            int idSubTareaInt = Integer.parseInt(txtIdBuscarSubTarea.getText());

            //Mensaje de Verificación
            int respuesta = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar la SubTarea?", "Confirmación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

            // 0 = Si
            if (respuesta == 0) {
                String mensaje = subTareaBO.eliminarSubTarea(idSubTareaInt);
                JOptionPane.showMessageDialog(null, mensaje);
                listarSubTarea(idTarea);
                cargarPorcentajes(idTarea);
            } else {
                JOptionPane.showMessageDialog(null, "Eliminación cancelada!", "Infomación", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarSubTareaActionPerformed

    private void txtIdBuscarSubTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdBuscarSubTareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdBuscarSubTareaActionPerformed

    private void btnAddSubTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSubTareaActionPerformed
         String idTareaString = txtIdTareaBuscar.getText();
         
         if (validacionIdTarea(idTareaString) == true) {
            limpiaCamposSubTarea();
            txtIdTareaBuscarSub.setText(idTareaString);
            listarSubTarea(Integer.parseInt(idTareaString));            
            this.jTabbedPane1.setSelectedIndex(2);
            btnGuardarSubTarea.setVisible(false);
            btnAgregarSubTarea.setVisible(true);
            cargarPorcentajes(Integer.parseInt(idTareaString));
        }
    }//GEN-LAST:event_btnAddSubTareaActionPerformed

    private void btnGuardarSubTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarSubTareaActionPerformed
        String finalizadoSubTarea;      
        int idSubTarea = Integer.parseInt(txtIdBuscarSubTarea.getText());
        String nombreSubTarea = txtNombreSub.getText();
        Boolean estadoSubTarea = CBFinalizado.isSelected();
        int idTarea = Integer.parseInt(txtIdTareaBuscarSub.getText());
        
        if (estadoSubTarea){
            finalizadoSubTarea = "1";
        } else{
            finalizadoSubTarea = "0";
        }
        
        subTarea.setIdSubTarea(idSubTarea);
        subTarea.setNombre(nombreSubTarea);
        subTarea.setFinalizado(finalizadoSubTarea);
        subTarea.setTareaIdTarea(idTarea);
        
        String mensaje = subTareaBO.modificarSubTarea(subTarea);
        
        JOptionPane.showMessageDialog(null, mensaje, "Infomación", JOptionPane.INFORMATION_MESSAGE);
        limpiaCamposSubTarea();
        limpiarCampos();
        listarSubTarea(idTarea);
        cargarPorcentajes(idTarea);
    }//GEN-LAST:event_btnGuardarSubTareaActionPerformed

    private boolean validacionIdTarea(String idTareaString) {
        
        if (Validar.campoVacio(idTareaString) == false) {
            mostrarMensaje("Error: \nEl campo Id Tarea está vacío! \nDebe completar el campo.");
            txtIdTareaBuscar.grabFocus();
            limpiarCampos();
            return false;
        }

        if (Validar.numeroEntero(idTareaString) == false) {
            mostrarMensaje("Error: \nEl dato ingresado debe ser numérico!");
            txtIdTareaBuscar.grabFocus();
            limpiarCampos();
            return false;
        }

        int idTareaInt = Integer.parseInt(idTareaString);
        String[] vector = new String[2];
        vector = tareaBO.buscarTarea(idTareaInt);
        String idTarea = vector[0];

        if (idTarea == "") {
            mostrarMensaje("Error: \nEl id ingresado no existe!");
            txtIdTareaBuscar.grabFocus();
            return false;
        }
        return true;
    }
    
    private boolean validacionIdSubTarea(String idSubTareaString, int idTarea) {
        
        if (Validar.campoVacio(idSubTareaString) == false) {
            mostrarMensaje("Error: \nEl campo está vacío! \nDebe completar el campo.");
            txtIdTareaBuscar.grabFocus();
            limpiaCamposSubTarea();
            return false;
        }

        if (Validar.numeroEntero(idSubTareaString) == false) {
            mostrarMensaje("Error: \nEl dato ingresado debe ser numérico!");
            txtIdTareaBuscar.grabFocus();
            limpiaCamposSubTarea();
            return false;
        }

        int idSubTareaInt = Integer.parseInt(idSubTareaString);
        String[] vector = new String[2];
        vector = subTareaBO.buscarSubTarea(idSubTareaInt,idTarea);
        String idSubTarea = vector[0];

        if (idSubTarea == "" || idSubTarea == null) {
            mostrarMensaje("Error: \nEl id ingresado no existe!");
            txtIdTareaBuscar.grabFocus();
            limpiaCamposSubTarea();
            return false;
        }
        return true;
    }



    // Limpiar campos de pestaña de agregar
    public void limpiarCampos() {
        txtNombre.setText("");
        txtDescripcion.setText("");
        cmbEstado.setSelectedItem("Seleccione");       
        cmbFuncion.setSelectedItem("Seleccione");
        cmbEncargado.setSelectedItem("Seleccione");
        jDateFechaInicio.setCalendar(null);
        jDateFechaTermino.setCalendar(null);
        
        txtNombreEd.setText("");
        txtDescripcionEd.setText("");
        cmbEstadoEd.setSelectedItem("Seleccione");
        cmbFuncionEd.setSelectedItem("Seleccione");
        cmbEncargadoEd.setSelectedItem("Seleccione");
        txtIdTareaBuscar.setText("");
        jDateFechaInicioEd.setCalendar(null);
        jDateFechaTerminoEd.setCalendar(null);
        
        txtIdTareaBuscar.setEnabled(true);
        
        //btnAddSubTarea.setEnabled(false);
         
    }

    public void limpiaCamposSubTarea(){
        txtIdBuscarSubTarea.setEnabled(true);
        btnAgregarSubTarea.setVisible(true);
        btnGuardarSubTarea.setVisible(false);
        txtIdBuscarSubTarea.setText("");
        txtNombreSub.setText("");
        CBFinalizado.setSelected(false);
    }

    private boolean validacionAgregar(String nombre, String estado, String funcion, String descripcion, String encargado) {
        
        if (Validar.campoVacio(nombre) == false) {
            mostrarMensaje("Error: \nEl nombre está vacío! \nDebe completar el campo.");
            txtNombre.grabFocus(); //Dar el enfoque al control
            return false;
        }
                
        if (jDateFechaInicio.getDate() == null) {
            mostrarMensaje("Error: \nLa fecha inicio está vacía! \nDebe completar el campo.");
            jDateFechaInicio.grabFocus(); //Dar el enfoque al control
            return false;
        }
        if (jDateFechaTermino.getDate() == null) {
            mostrarMensaje("Error: \nLa fecha termino está vacía! \nDebe completar el campo.");
            jDateFechaTermino.grabFocus(); //Dar el enfoque al control
            return false;
        }
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-YYYY");
        String fechaInicio = dFormat.format(jDateFechaInicio.getDate());
        String fechaTermino = dFormat.format(jDateFechaTermino.getDate());
        try {
            Date fecha1 = new SimpleDateFormat("dd-MM-yyyy").parse(fechaInicio);
            Date fecha2 = new SimpleDateFormat("dd-MM-yyyy").parse(fechaTermino);
            if(fecha1.after(fecha2)){
                mostrarMensaje("Error: \nLa fecha Inicio no puede ser mayor que la de término! \nDebe completar el campo.");
                jDateFechaTermino.grabFocus();
                return false;
            }
        } catch (ParseException ex) {
            Logger.getLogger(FrmTarea.class.getName()).log(Level.SEVERE, null, ex);
            return false;
        }
        
        if (Validar.campoVacio(estado) == false || estado == "Seleccione" ) {
            mostrarMensaje("Error: \nEl estado está vacío! \nDebe completar el campo.");
            cmbEstado.grabFocus(); //Dar el enfoque al control
            return false;
        }

        if (Validar.campoVacio(funcion) == false || funcion == "Seleccione") {
            mostrarMensaje("Error: \nLa función está vacío! \nDebe completar el campo.");
            cmbFuncion.grabFocus(); //Dar el enfoque al control
            return false;
        }
        
        if (Validar.campoVacio(encargado) == false || encargado == "Seleccione") {
            mostrarMensaje("Error: \nEl encargado no es válido! \nDebe completar el campo.");
            cmbEncargado.grabFocus();
            return false;
        }
        
        if (Validar.campoVacio(descripcion) == false) {
            mostrarMensaje("Error: \nLa descripción está vacía! \nDebe completar el campo.");
            txtDescripcion.grabFocus(); //Dar el enfoque al control
            return false;
        }

        
        
        return true;
    }

    private boolean validacionEdicion(String nombre, String estado, String funcion, String descripcion, String encargado) {
        
        if (Validar.campoVacio(nombre) == false) {
            mostrarMensaje("Error: \nEl nombre está vacío! \nDebe completar el campo.");
            txtNombreEd.grabFocus(); //Dar el enfoque al control
            return false;
        }
                
        if (jDateFechaInicioEd.getDate() == null) {
            mostrarMensaje("Error: \nLa fecha inicio está vacía! \nDebe completar el campo.");
            jDateFechaInicioEd.grabFocus(); //Dar el enfoque al control
            return false;
        }
        if (jDateFechaTerminoEd.getDate() == null) {
            mostrarMensaje("Error: \nLa fecha termino está vacía! \nDebe completar el campo.");
            jDateFechaTerminoEd.grabFocus(); //Dar el enfoque al control
            return false;
        }
        
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-YYYY");
        String fechaInicio = dFormat.format(jDateFechaInicioEd.getDate());
        String fechaTermino = dFormat.format(jDateFechaTerminoEd.getDate());
        try {
            Date fecha1 = new SimpleDateFormat("dd-MM-yyyy").parse(fechaInicio);
            Date fecha2 = new SimpleDateFormat("dd-MM-yyyy").parse(fechaTermino);
            if(fecha1.after(fecha2)){
                mostrarMensaje("Error: \nLa fecha Inicio no puede ser mayor que la de término! \nDebe completar el campo.");
                jDateFechaTerminoEd.grabFocus();
                return false;
            }
        } catch (ParseException ex) {
            Logger.getLogger(FrmTarea.class.getName()).log(Level.SEVERE, null, ex);
            return false;
        }
        
        if (Validar.campoVacio(estado) == false || estado == "Seleccione" ) {
            mostrarMensaje("Error: \nEl estado está vacío! \nDebe completar el campo.");
            cmbEstadoEd.grabFocus(); //Dar el enfoque al control
            return false;
        }

        if (Validar.campoVacio(funcion) == false || funcion == "Seleccione") {
            mostrarMensaje("Error: \nLa función está vacío! \nDebe completar el campo.");
            cmbFuncionEd.grabFocus(); //Dar el enfoque al control
            return false;
        }
        
        if (Validar.campoVacio(encargado) == false || encargado == "Seleccione") {
            mostrarMensaje("Error: \nEl encargado no es válido! \nDebe completar el campo.");
            cmbEncargadoEd.grabFocus();
            return false;
        }
        
        if (Validar.campoVacio(descripcion) == false) {
            mostrarMensaje("Error: \nLa descripción está vacía! \nDebe completar el campo.");
            txtDescripcionEd.grabFocus(); //Dar el enfoque al control
            return false;
        }

        return true;
    }

    //Método común para mostrar mensajes
    private void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje);
    }

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
    public void frmTarea() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTarea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CBFinalizado;
    private javax.swing.JButton btnAddSubTarea;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregarSubTarea;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarSubTarea;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarSubTarea;
    private javax.swing.JButton btnGuardarSubTarea;
    private javax.swing.JButton btnLimipiarEd;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLimpiarSubTarea;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnListar1;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cmbEncargado;
    private javax.swing.JComboBox<String> cmbEncargadoEd;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbEstadoEd;
    private javax.swing.JComboBox<String> cmbFuncion;
    private javax.swing.JComboBox<String> cmbFuncionEd;
    private com.toedter.calendar.JDateChooser jDateFechaInicio;
    private com.toedter.calendar.JDateChooser jDateFechaInicioEd;
    private com.toedter.calendar.JDateChooser jDateFechaTermino;
    private com.toedter.calendar.JDateChooser jDateFechaTerminoEd;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JLayeredPane jLayeredPane6;
    private javax.swing.JLayeredPane jLayeredPane7;
    private javax.swing.JLayeredPane jLayeredPane8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCantSubTareas;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombre10;
    private javax.swing.JLabel lblNombre11;
    private javax.swing.JLabel lblNombre12;
    private javax.swing.JLabel lblNombre13;
    private javax.swing.JLabel lblNombre18;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblNombre3;
    private javax.swing.JLabel lblNombre4;
    private javax.swing.JLabel lblNombre5;
    private javax.swing.JLabel lblNombre6;
    private javax.swing.JLabel lblNombre7;
    private javax.swing.JLabel lblNombre8;
    private javax.swing.JLabel lblNombre9;
    private javax.swing.JLabel lblPorcentajeAvance;
    private javax.swing.JLabel lblUnidadEd;
    private javax.swing.JLabel lblUnidadEd1;
    private javax.swing.JTable tblSubTarea;
    private javax.swing.JTable tblTarea;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextArea txtDescripcionEd;
    private javax.swing.JTextField txtIdBuscarSubTarea;
    private javax.swing.JTextField txtIdTareaBuscar;
    private javax.swing.JTextField txtIdTareaBuscarSub;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreEd;
    private javax.swing.JTextField txtNombreSub;
    // End of variables declaration//GEN-END:variables
}
