package view;

import bo.ClienteBO;
import bo.UsuarioBO;
import dao.UsuarioDAO;
import bo.UnidadBO;
import dao.UnidadDAO;
import bo.ProcesoBO;
import dao.ProcesoDAO;
import bo.EstadoBO;
import dao.EstadoDAO;
import entity.Funcion;
import bo.FuncionBO;
import dao.ClienteDAO;
import dao.FuncionDAO;
import entity.Unidad;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import test.Validar;

import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import static java.util.logging.Level.parse;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

// LIBRERIA DE ENCRIPTACIÓN
// ALGORITMO DE ENCRIPTACIÓN SHA 512 HEX
import org.apache.commons.codec.digest.DigestUtils;

/**
 *
 * @author Kevin
 */
public class FrmUnidad extends javax.swing.JFrame {

    Unidad unidad = new Unidad();
    private UnidadBO unidadBO = new UnidadBO();
    private UnidadDAO unidadDAO = new UnidadDAO();

    private ClienteBO clienteBO = new ClienteBO();

    public FrmUnidad() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Módulo - Gestión de Unidades");
        setResizable(false);
        listarUnidad();
        listarCliente();
        
        //Integración de icono en la ventana de titulo de la ventana
        BufferedImage image = null;
        try {
            image = ImageIO.read(new File("src/icons/icons32px/logo30px.png"));
        } catch (IOException ex) {
            Logger.getLogger(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        setIconImage(image);
    }

    public void listarUnidad() {
        unidadBO.listarUnidad(tblUnidad);
    }

    public void listarCliente() {
        clienteBO.listarClienteCmb(cmbCliente);
        clienteBO.listarClienteCmb(cmbClienteEd);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        lblUnidad = new javax.swing.JLabel();
        cmbCliente = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jLabel11 = new javax.swing.JLabel();
        txtIdUnidadBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        btnEditar = new javax.swing.JButton();
        btnLimipiarEd = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblNombre1 = new javax.swing.JLabel();
        txtNombreEd = new javax.swing.JTextField();
        lblUnidadEd = new javax.swing.JLabel();
        cmbClienteEd = new javax.swing.JComboBox<>();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUnidad = new javax.swing.JTable();
        btnListar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1459, 750));
        setPreferredSize(new java.awt.Dimension(1459, 750));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1200, 700));
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de la Unidad", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jLayeredPane1.setMaximumSize(new java.awt.Dimension(700, 588));
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(700, 588));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombre.setText("Nombre:");
        jLayeredPane1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLayeredPane1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 300, -1));

        btnAgregar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/anadir.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.setIconTextGap(20);
        btnAgregar.setPreferredSize(new java.awt.Dimension(100, 25));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 150, 40));

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/limpiar32px.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setIconTextGap(20);
        btnLimpiar.setPreferredSize(new java.awt.Dimension(100, 25));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 150, 40));

        lblUnidad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUnidad.setText("Cliente:");
        jLayeredPane1.add(lblUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        cmbCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLayeredPane1.add(cmbCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 300, -1));

        jPanel1.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 580, 420));
        jLayeredPane1.getAccessibleContext().setAccessibleName("Datos del");

        jTabbedPane1.addTab("Agregar Unidad", jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(573, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Unidad por Id", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jLayeredPane4.setMaximumSize(new java.awt.Dimension(600, 94));
        jLayeredPane4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Id Unidad:");
        jLayeredPane4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        txtIdUnidadBuscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLayeredPane4.add(txtIdUnidadBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 298, -1));

        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/buscar32px.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setIconTextGap(20);
        btnBuscar.setPreferredSize(new java.awt.Dimension(100, 25));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jLayeredPane4.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 150, 40));

        jPanel2.add(jLayeredPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 29, 710, 90));

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edición de Unidad", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jLayeredPane3.setMaximumSize(new java.awt.Dimension(600, 495));
        jLayeredPane3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEditar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/guardar32px.png"))); // NOI18N
        btnEditar.setText("Guardar");
        btnEditar.setIconTextGap(20);
        btnEditar.setPreferredSize(new java.awt.Dimension(100, 25));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jLayeredPane3.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 150, 40));

        btnLimipiarEd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLimipiarEd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/limpiar32px.png"))); // NOI18N
        btnLimipiarEd.setText("Limpiar");
        btnLimipiarEd.setIconTextGap(20);
        btnLimipiarEd.setPreferredSize(new java.awt.Dimension(100, 25));
        btnLimipiarEd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimipiarEdActionPerformed(evt);
            }
        });
        jLayeredPane3.add(btnLimipiarEd, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 150, 40));

        btnEliminar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/eliminar32px.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setIconTextGap(20);
        btnEliminar.setPreferredSize(new java.awt.Dimension(100, 25));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jLayeredPane3.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 150, 40));

        lblNombre1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombre1.setText("Nombre:");
        jLayeredPane3.add(lblNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        txtNombreEd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLayeredPane3.add(txtNombreEd, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 300, -1));

        lblUnidadEd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUnidadEd.setText("Cliente:");
        jLayeredPane3.add(lblUnidadEd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        cmbClienteEd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLayeredPane3.add(cmbClienteEd, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 300, -1));

        jPanel2.add(jLayeredPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 710, 320));

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro de Unidades", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);

        tblUnidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblUnidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblUnidad.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jScrollPane1.setViewportView(tblUnidad);

        jLayeredPane2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 54, 640, 340));

        btnListar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/listar32px.png"))); // NOI18N
        btnListar.setText("Listar");
        btnListar.setIconTextGap(20);
        btnListar.setPreferredSize(new java.awt.Dimension(100, 25));
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        jLayeredPane2.add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 137, 38));

        jPanel2.add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(793, 29, -1, 520));

        jTabbedPane1.addTab("Ver Unidad", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1459, 610));

        btnVolver.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons32px/volver32px.png"))); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.setIconTextGap(20);
        btnVolver.setPreferredSize(new java.awt.Dimension(100, 25));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 640, 165, 41));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        new FrmPanelGeneral().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed


    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        String idUnidadString = txtIdUnidadBuscar.getText();

        if (validacionIdUnidad(idUnidadString) == true) {

            String[] vector = new String[3];
            int idFuncionInt = Integer.parseInt(txtIdUnidadBuscar.getText());
            vector = unidadBO.buscarUnidad(idFuncionInt);

            txtNombreEd.setText(vector[1]);

            String idClientString = vector[2];
            String[] vectorCliente = new String[2];
            int idClienteInt = Integer.parseInt(idClientString);
            vectorCliente = clienteBO.buscarCliente(idClienteInt);
            String clienteNombre = vectorCliente[1];
            cmbClienteEd.setSelectedItem(clienteNombre);
            
            // (10-12-2020) (Emilio) (se bloquea o deshabilita el campo de busqueda)
            txtIdUnidadBuscar.setEnabled(false);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed


    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        String nombre = txtNombre.getText();
        String clienteString = cmbCliente.getSelectedItem().toString();
        int clienteIndex = cmbCliente.getSelectedIndex();

        if (validacionAgregar(nombre, clienteString) == true) {

            unidad.setNombreDepartamento(nombre);
            unidad.setClienteIdCliente(clienteIndex);

            String mensaje = unidadBO.agregarUnidad(unidad);
            JOptionPane.showMessageDialog(null, mensaje, "Infomación", JOptionPane.INFORMATION_MESSAGE);
            //System.out.println("Mensaje: \n" + mensaje);

            limpiarCampos();
            listarUnidad();
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        /*if (this.jTabbedPane1.getSelectedIndex() == 1) {

        }*/
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        listarUnidad();
    }//GEN-LAST:event_btnListarActionPerformed


    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String idUnidadString = txtIdUnidadBuscar.getText();

        if (validacionIdUnidad(idUnidadString) == true) {
            int idUnidadInt = Integer.parseInt(txtIdUnidadBuscar.getText());

            int respuesta = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar la Unidad?", "Confirmación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

            if (respuesta == 0) {
                String mensaje = unidadBO.eliminarUnidad(idUnidadInt);
                /*System.out.println("\n\n***********************************");
                System.out.println("Mensaje Eliminar funcion: " + mensaje);
                System.out.println("\n\n***********************************");*/
                JOptionPane.showMessageDialog(null, mensaje);
                limpiarCampos();
                listarUnidad();
            } else {
                JOptionPane.showMessageDialog(null, "Eliminación cancelada!", "Infomación", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimipiarEdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimipiarEdActionPerformed
        // (10-12-2020) (Emilio) (Limpieza y habilitación de los campos)
        limpiarCampos();
    }//GEN-LAST:event_btnLimipiarEdActionPerformed


    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        String idUnidad = txtIdUnidadBuscar.getText();

        String nombreEd = txtNombreEd.getText();
        String clienteStringEd = cmbClienteEd.getSelectedItem().toString();
        int clienteIndexEd = cmbClienteEd.getSelectedIndex();

        if (validacionEdicion(nombreEd, clienteStringEd) == true) {

            int idUnidadInt = Integer.parseInt(idUnidad);

            unidad.setIdUnidad(idUnidadInt);
            unidad.setNombreDepartamento(nombreEd);
            unidad.setClienteIdCliente(clienteIndexEd);

            String mensaje = unidadBO.modificarUnidad(unidad);
            JOptionPane.showMessageDialog(null, mensaje, "Infomación", JOptionPane.INFORMATION_MESSAGE);
            //System.out.println("Mensaje: \n" + mensaje);

            limpiarCampos();
            listarUnidad();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new FrmPanelGeneral().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private boolean validacionIdUnidad(String idUnidadString) {

        if (Validar.campoVacio(idUnidadString) == false) {
            mostrarMensaje("Error: \nEl campo está vacío! \nDebe completar el campo.");
            txtIdUnidadBuscar.grabFocus();
            limpiarCampos();
            return false;
        }

        if (Validar.numeroEntero(idUnidadString) == false) {
            mostrarMensaje("Error: \nEl dato ingresado debe ser numérico!");
            txtIdUnidadBuscar.grabFocus();
            limpiarCampos();
            return false;
        }

        int idUnidadInt = Integer.parseInt(idUnidadString);
        String[] vector = new String[2];
        vector = unidadBO.buscarUnidad(idUnidadInt);
        String idUnidad = vector[0];

        if (idUnidad == "") {
            mostrarMensaje("Error: \nEl id ingresado no existe!");
            txtIdUnidadBuscar.grabFocus();
            limpiarCampos();
            return false;
        }
        return true;
    }

    // Limpiar campos de pestaña de agregar
    public void limpiarCampos() {
        txtNombre.setText("");
        cmbCliente.setSelectedItem("Seleccione");
        txtNombreEd.setText("");
        cmbClienteEd.setSelectedItem("Seleccione");
        txtIdUnidadBuscar.setText("");
        
        // (10-12-2020) (Emilio) (habilitación de campo de busqueda)
        txtIdUnidadBuscar.setEnabled(true);
    }

    private boolean validacionAgregar(String nombre, String clienteString) {

        if (Validar.campoVacio(nombre) == false) {
            mostrarMensaje("Error: \nEl nombre está vacío! \nDebe completar el campo.");
            txtNombre.grabFocus();
            return false;
        }

        if (Validar.campoVacio(clienteString) == false || clienteString.equals("Seleccione")) {
            mostrarMensaje("Error: \nIngrese un cliente!");
            cmbCliente.grabFocus();
            return false;
        }

        return true;
    }

    private boolean validacionEdicion(String nombreEd, String clienteStringEd) {

        if (Validar.campoVacio(nombreEd) == false) {
            mostrarMensaje("Error: \nEl nombre está vacío! \nDebe completar el campo.");
            txtNombreEd.grabFocus();
            return false;
        }

        if (Validar.campoVacio(clienteStringEd) == false || clienteStringEd.equals("Seleccione")) {
            mostrarMensaje("Error: \nIngrese un cliente!");
            cmbCliente.grabFocus();
            return false;
        }

        return true;
    }

    //Método común para mostrar mensajes
    private void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje);
    }

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
    public void frmUnidad() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUnidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUnidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUnidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUnidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUnidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimipiarEd;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cmbCliente;
    private javax.swing.JComboBox<String> cmbClienteEd;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblUnidad;
    private javax.swing.JLabel lblUnidadEd;
    private javax.swing.JTable tblUnidad;
    private javax.swing.JTextField txtIdUnidadBuscar;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreEd;
    // End of variables declaration//GEN-END:variables
}
